# 第五十章 吞噬梦想之人 {-}

七月十七日，如水接待了竹中隆重的来访。隆重是丰前高田一万三千石的大名，同时也是以秀吉军师而闻名的已故竹中半兵卫的堂弟，因此他与如水也交情深厚，偶尔会心血来潮，乘船环绕国东半岛，顺道来中津游玩。不过，这一天的访问，或许隐藏着更深一层的意图。

"我们去城下逛逛吧。"

如水将老友的堂弟带到了豪商伊予屋弥右卫门的宅邸。

在接受款待后，隆重心情愉快地告辞离开了。据说就在他刚走不久，大坂府邸的留守役栗山善助和母里太兵卫派出的密使野间源兵卫就冲进了伊予屋。读完密信的老人家挣扎着站起身，摇摇晃晃地在房间里踱步——年轻时如水曾在伊丹城的地窖里被囚禁一年，导致他的左腿到现在都行动不便。

"是有什么不好的消息吗？" 伊予屋小心翼翼地询问道。

"不不，是治部少辅他，" 如水高兴地抖动着手中的急报，

"他通知我说，已经举兵了。"

"石田大人他！"

"要天下大乱了。" 老人又重复了一遍。"要有一场惊天动地的大乱了。"

他心想：要是不天下大乱可就麻烦了。毕竟，自己可是等了这消息整整两年啊。

<p style="margin-bottom:3em;"></p>

在九州的大名中，最先接到大坂剧变的，自然就是如水。在这种情况下，情报就是力量。

如水非常重视情报。黑田家自行培养的情报收集人员，大多或是卖眼药的，或是马贩，他们被统称为"草"。如水将相当数量的"草"分成四组，根据所需情报的种类灵活运用。问题在于如何将"草"搜集到的情报尽快送达中津，而在这方面，老人也展现了他周详缜密的一面。去年离开大坂时，如水挑选了三艘速度飞快的蜈蚣船，将它们分别部署在大坂的天满、备后的靭、周防的上关这三处。目的是以接力的方式，将上方的变乱消息逐次飞报回来。密使仅用三天就抵达中津，正是得益于此。

"对了，赶快去把竹中大人追回来！" 如水吩咐在走廊上等候的家臣。"就说恳请他再次回来一趟。"

<p style="margin-bottom:3em;"></p>

如水是个热心肠的人。他想把这份珍贵的、花费了巨大成本才获得的情报，首先告诉这位仰慕自己、特意远道而来中津的大名。同时，竹中家虽然仅有三百石左右，但其拥有的军事力量也让他觉得极具吸引力，没有理由让那支力量闲置不用。如水的思维中没有"浪费"这个概念，总是瞬间就这样运转起来。

"就在刚才，" 如水对返回的隆重说道。"接到了大坂留守役的报告，说治部少辅已经举兵了。"

"治部少辅！他终于动手了吗！"

"内府大人此刻想必在暗自窃喜吧。"

"您这么说的话……" 

隆重的脸色稍微阴沉了一下。

"依如水老您的判断，是内府会获胜吗？"

"大概会是那样吧。"

"您能肯定吗？"

"我是这么认为的。"

"……"

"莫非，伊豆守大人您，难道给留守役们下了命令，要他们支持治部少辅……？"

"绝无此事！"

伊豆守隆重猛烈地摇头否认。

<p style="margin-bottom:3em;"></p>

隆重曾是秀吉麾下的马廻组头，在庆长之役中荣膺六名军监之一。深受太阁恩泽的感念之情，至今仍留存在这位武人心中。因此，隆重自然属于大坂一方，在回国时曾明确指示重臣们："倘若局势有变，当毫不犹豫地支持治部少辅。"

事实上，大坂的留守部队此时已经驻守在久宝寺町桥一带。对于隆重而言，如果三成如此轻易地落败，会让他很为难。

在"不希望三成轻易落败"这一点上，如水也完全赞同。虽然最终家康可能会获胜，但如水希望三成也能奋力拼搏一番。败北是无可奈何的，但在那之前，他希望三成能给内府造成难以轻易东山再起的重创——

他就是这样的心情。

老人陶醉地想象着那番景象：在某个仿佛散落着两军士兵尸骸的草原般的地方，想象中的家康站在那里。他虽然赢了，却显得相当疲惫。家康刚要下令"奏响凯歌"，却突然疑惑地转向一方。他似乎听到了震撼大地的数万军马蹄声。下一刻，疑惑的表情变成了极度的狼狈。家康面如土色，注意到了那支正朝自己冲杀而来的、毫发无伤的军队——

如水微微一笑。当然，那时候率领那支生力军的，想必就是老夫我吧。真是一幅令人心旷神怡的想象图。

从伊予屋返回中津城的老人命令家臣全体登城，并宣布道：

"自此，我们将征服附近诸国。速速做好出征准备。"

<p style="margin-bottom:3em;"></p>

老臣们的脸上写满了惊愕。虽说命令他们准备，但能派得上用场的武士，都已经被长政全部带往关东，留在中津的仅有七百人左右。而且其中大多是文官，或者已是老人。这样的兵力别说攻取邻近地区了，就连中津城本身都可能被邻近的三成党羽攻陷。按照常理，此时应当据守城中，屏息凝神，等待风暴过去才是。

如水没有等待老臣们说出反对的话。这帮人在想什么，这位老人光凭"气味"就能明白。

"你们跟随我多年，看来却还不明白我的器量。确实，九州地区治部少辅的党羽为数不少。"

如水开始对诸侯进行分类。

会加入东军的，大概只有加藤和寺泽吧。诸侯之中，无论是岛津、锅岛、小西、柳川的立花、久留米的毛利秀包、臼杵的太田一吉、小仓的毛利胜信、佐土原的岛津丰久、富来的垣见一直、福岛的筑紫广门，还是安岐的熊谷直盛，几乎所有人都会支持三成。他觉得，刚才才分手的竹中隆重，恐怕也算作这边的比较稳妥。能期待保持中立的，大概只有五岛的五岛玄雅、平户的松浦镇信、日野江的有马晴信、大村的大村喜前这几个人吧。剩下的，恐怕要等战事揭晓才能知道。至于为什么连尚未表明立场的岛津、锅岛都划入了西军，如水自己也难以清楚说明。硬要解释的话，也只能说那同样是凭"气味"判断出来的。

"但是，一点也用不着害怕。他们有一个共同的弱点。那就是，除了岛津和锅岛，他们大部分人已经率领军队前往上方了。留在城里的兵力，能有两三百人的大名恐怕很少吧。留守的人现在大概正屏息凝神，等待风暴过去呢。就和你们一样。要是我们黑田家率领一万大军压境，会怎么样呢？"

“那些家伙会逃跑，留下的将是一座座空无一人的、完整的城池。我只需要把它们统统"收入囊中"就行了。”

丰后地区有十座城池。如水首先想把这些纳入掌中。

"问题在于那一万兵力，这个就交给我来办吧。"


<p style="margin-bottom:3em;"></p>

如水当天就着手征兵。

"不一定非得是武士或浪人不可！依靠父母的年轻人、隐居者、农民、町人、工匠……但凡有心想举旗立功者，统统让他们聚集到中津来——就这样把告示传遍各地。"

从那天起，大手门便开始吞噬大量的浪人。那光景简直如同化装游行。应召而来的人大部分曾是地方武士，但装备齐全者却寥寥无几。穿着不配套的铠甲、骑着瘦马的已经算是上等货色了；有的像是卖掉了盔甲，只戴着护胫；有的穿着纸制的、用朱红色画着家徽的、类似阵羽织的外衣；其中甚至还有人不像戴头盔，反倒戴着像花斗笠舞那种斗笠。虽然模样千奇百怪，但士气却异常高昂。

如水让人把这群"一旗组"带到面对大广间的中庭。房间里，已经有好几处特意堆起了金银小山，好像在炫耀似得。

男人们都默默地呆立着。

"这是何等巨量的钱财啊！"一个人感慨道。"有这么多钱，连整个日本都能买下来吧。"

说实话，总共有多少，连如水自己也不知道确切的数目。总之就是：他耗费五十五年积蓄的全部财富，此刻都在那里了。

<p style="margin-bottom:3em;"></p>

如水绝对算不上是一位慷慨大方的主人。说得直白点，像他这么吝啬的大名很少见。就连把穿旧了的布袜处理给家臣时，他也从不忘记索要五文或六文钱。

"我会给你宅邸和米，所以你要在庭院里种上梅树。"如水经常这么说：

"这样就能做出梅干，吃饭就不成问题了。"


<p style="margin-bottom:2em;"></p>

还有这样一个故事流传下来：到了吃瓜的季节，乡民进献了许多瓜，如水招待大家吃瓜，连小姓和僧侣也来吃。奇怪的是，如水不停地吩咐"皮要削厚点"。

正当大家疑惑不解时，如水叫来厨房的管事，这样吩咐道：

"把那些瓜皮用盐腌起来。在厨房吃饭的人，有时菜会不够吧。就用来添补那个。茄子的蒂也好，切下来的蔬菜边角料也好，都不准扔掉。全部用盐腌起来，在没有菜的时候派上用场。"


<p style="margin-bottom:2em;"></p>

如水的金钱观念，是从卖眼药的祖父和父亲那里学到的。人是为钱而动的，虽然这可能不是什么好事，但人就是如此。如水打算用钱来收买浪人们的心。这些钱是他点着灯火，从指甲缝里省下来积攒的，但要将它们散出去，他却一点也不觉得可惜。对他而言，这是为了获取更巨大财富的投资。人是为了自己的梦想，为了自己的审美意识而花钱的。现在不用，更待何时？他就是这样的心情。

"这些钱发给他们。"

如水说道。

男人们一下子动了起来。那气势简直像小山在移动一般，排起了好几条长队。男人们按照登记的顺序，领取临时筹备金：骑马的可以领银三百匁，步卒可以领永乐钱一贯。

混乱之中，也有不守规矩的人排队领了两三次，如水反而斥责了那些对此吹毛求疵的官吏：

"我平日节俭积蓄金钱，就是为了这种时候。就算他们领了双份，只要肯作为我方效力，那就行了。况且，同一个人来两次，不也能提振声势吗？重要的是'聚集了尽可能多的人'这样的风声。"这位老人总能精准把握事物的本质。

<p style="margin-bottom:3em;"></p>

说到本质，还有这样一件事：在招募佣兵时，如水并没有要求他们提供身份担保人。家臣们对此深感忧虑，但结果再次证明了如水在收揽人心方面的精妙之处。因为浪人们绝不会做出让自己在所申报的身份面前感到羞愧的行为。换句话说，他们反而会拼命战斗，力求接近自己所申报的那个身份。

总之，通过第一次招募，如水得到了三千六百人。令人欣喜的传闻开始流传开来。

"金银成山，米粮成山，尽在如水城中。"

据说这消息甚至跨海传到了中国地区，乃至播磨。就这样，这场"化装游行"一直持续到九月初。据《黑田家旧记》记载，佣兵人数最终达到了九千人。

<p style="margin-bottom:3em;"></p>

在此之后四五天，三成的特使抵达了中津。

"来的是什么人？"

如水首先询问了使者的名字。近侍回答了某人的名字，但如水对此毫无印象。派来一个无名官僚作为使者，如水从中看到了对方对自己的评价。老人叹了口气。

“我不喜欢治部少辅。但是，如果那个男人亲自来到中津城，抛下一切，向我哀恳求助的话，说不定我多少会有些动摇。即使要冒着成为俘虏的风险，如果是我，我一定会那么做的。”

老人像缠足妇人般摇摇晃晃地走向使者等候的书院，一边低声自语：

"治部少辅，果然你还是会输啊。连我的心都无法收揽，又怎能取得天下呢？”

<p style="margin-bottom:3em;"></p>

然而在下一瞬间，如水猛地停下了脚步。那时老人意识到，自己其实也和三成一样，同样没能收揽那个男人的心。彼此彼此罢了。嘛，两个中等之才，就互相勉励吧。

如水再次摇摇晃晃地走了起来。

"阁下与太阁殿下交情深厚。恳请务必助我方一臂之力。"

年轻的使者慷慨陈词。说是只要消灭家康，恩赏任凭开口。如水显得大为心动。

"好吧，我愿相助。我将即刻上京，面授讨伐内府的秘策。" 

不过，如水附加了条件：

"方才说恩赏可随我意，为避免日后纠纷，希望能明确下来。因此，我希望领有九州之内的七国。"

<p style="margin-bottom:3em;"></p>

出乎意料，使者爽快地答应了。看来是事先得到了三成的授意。无论如何，这个男人并没有就恩赏多寡进行讨价还价的立场。

如水自然要求对方递交誓书。三成的使者于次日，与负责接收誓书的宇治勘七一同离开了中津。

"七国吗……" 如水感慨万千地反复念叨着。"不坏啊。" 

老臣们并未怀疑主人的变节。事实上，为了七国，这位老人确实有着冷酷到甚至可能牺牲独子长政的一面。

<p style="margin-bottom:3em;"></p>

 井上九郎右卫门作为老臣代表，来到如水面前。

"我们必须向您请教真意。若是对双方都示好，我们会很为难的。"

"你们这是来给我这老头子出难题了啊。" 如水说道。

"是的。"

"不必担心。我的心意丝毫未变。"

"那为何派勘七……"

"是想问为何派他去取誓书吧？是为了争取时间。利用这段时间完成出兵的准备，顺便探查大坂的形势。"

老人张开没牙的嘴，高兴地笑了。

