# 第五十四章 归乡 {-}

西军对伏见城的攻击，始于十九日的薄暮时分。不过，这天从远处包围城池的，主要是九州的中小大名，他们只是向城门方向进行了几次不成规模的、近乎敷衍的射击而已。

有那么一瞬间，元忠想道：要不要主动出击呢？如果现在打开城门出击，首战的胜利想必是确凿无疑的。但是，元忠不得不眼睁睁地放过了这个良机。因为与攻城方一样，己方的斗志也谈不上多么旺盛。

在西军按照预料之中来袭的这一天，这位守城主将从清晨起就开始忙碌。上午八时，元忠巡视了城外，烧毁了可能妨碍防御的民宅，随后又确定了诸位部将新的部署。这是因应木下胜俊逃亡而采取的措施。由此，元忠负责守卫本丸，内藤弥次右卫门家长及其子小市郎元长守卫西之丸，松平主殿助家忠与松平五左卫门近正则守卫三之丸。然而，部将们在接到新部署的命令后，却迟迟没有从座位上起身。

他们似乎有话想说。果不其然，仿佛代表三人一般，近正开口了：

“待在这里是等不到援军的。一旦被大军包围，后悔可就来不及了！”

近正像是带着怒气般这样说道。那口吻简直就像恨不得立刻逃回关东去似的。

<p style="margin-bottom:2em;"></p>

元忠忽然很想放声大笑。并非因为此事可笑，而是因为这感觉既可笑又可悲，甚至连他自己也分不清究竟是哪一种。那一刻，攫住元忠的，是一种仿佛横亘在自己与部将们之间的巨大隔阂感。总之，在他看来，这些到了这般关头还对生念念不忘的男子，显得异常幼稚。事到如今再来讨论笼城战的得失，岂不是有点太迟了吗？

“诸位的忧虑，我不是不明白。”元忠说道。

虽然有些遗憾，但元忠心想：必须让这些人陪着自己一同赴死。可以说，这三人是为了使其死亡显得庄严而必不可少的工具。

“诸位的忧虑我不是不明白，然而，即便此刻弃城而走，也无法保证能平安抵达关东。最终恐怕会腹背受敌，被乱民取了首级。至于说到没有援军这一点，我个人也实在难以苟同。只要死守城池，主公必定会赶来救援的。”

元忠慢条斯理地说完了这番话语。

令人不快的沉默降临了。显然，那三人从一开始就不相信。

“看来你们并未信服啊。”元忠说。

三人依旧一言不发。

“若不能信服，那就悉听尊便吧。”

元忠砰地一声把话说绝了。那是一种“有本事逃就逃逃看”的心情。

部将们只好心不甘情不愿地回到了各自的岗位。

<p style="margin-bottom:3em;"></p>

然而，并非所有人都是贪生怕死之辈。渴望赴死而进城的人也不在少数。首先，因毛利辉元入城而被逐出西之丸的佐野纲正，脸色大变地奔了进来。

“麻烦的行李都已寄存在大和的朋友那里了^[佐野纲正在庆长五年（1600年）的会津征伐期间，作为大坂城西之丸的留守居负责守备。西军举兵后，他以交出西之丸为条件，带着德川家康的侧室阿茶局、阿胜、阿万前往八幡安置。随后将侧室们托付给熟人，于7月17日率领同心、与力进入德川方据守的伏见城。在伏见城之战中，他亲自操作大炮等，坚守二之丸，最终于7月29日战死。]。请让我死在这里吧。”

纲正如此说道。

元忠没有拒绝。如果家康把侍妾托付给自己，自己想必也会这么做吧。

顺带一提，纲正后来是在乱射火枪时，因枪管破裂而死的。似乎是不小心装填了双重弹药所致。简直就像是被自己射出的子弹打死的一样。但他死后，家康对纲正的忠节并未感到喜悦。家康以“纲正为了自己的武名，把托付给他的女人们硬塞给他人，未经允许便死在伏见城”为理由，没收了纲正三千石的家禄，只允许其嫡子成职继承五百俵。

<p style="margin-bottom:2em;"></p>

继纲正之后，宇治的茶师上林竹庵也来了。

上林家与德川的缘分不浅。竹庵的兄长久茂，在那次本能寺之变时，曾帮助家康一行逃离畿内；而竹庵本人也在十多年前下赴冈崎，致力于三河茶的栽培与推广。他的俸禄是年百石。即使回到宇治后，竹庵政重也未曾忘记自己被当作家臣般对待的三河时代。不，随着时间的流逝，那段回忆反而愈发鲜明耀眼。

据说，一听说伏见城危急，竹庵便立刻背起一个行李包，从宇治飞奔而出。

“你的心意我很感激，但是……”

元忠拒绝了竹庵的请求。

如果让茶师也进城，恐怕会被人说鸟居是因为人手不足，连商人都搜罗来了。

“我明白了。您说的在理，我也不再强求了。”

竹庵垂下了肩膀。

“但是，这样我无法回宇治。即使给您添麻烦，也请让我在此当场切腹吧。”

元忠被震撼了。竹庵那近乎呢喃的声音里，蕴含着一种让人不得不为之战栗的力量。

最终，竹庵被分配到了太鼓丸。茶师收集茶袋，制作了背旗。他没有戴头盔，而是在头上缠了一条红色的头巾。以这副奇异的装束，茶师向锅岛队发起了突击，再也没有回来。

家康没有忘记这位不忘百石恩情的茶师，厚待了他，任命其兄长久茂为宇治代官，并进一步指定其为幕府、诸藩以及茶道宗匠们的专卖茶商。这与纲正的情况可谓天差地别。

<p style="margin-bottom:2em;"></p>

十八日傍晚，当时位于近江的德川家知行地代官岩间兵库、平冈弥左卫门等人，率领着甲贺的忍者五六十名入城；几刻之后，又有一位浪人叩响了城门。是平冈的兄长正治，他说想和弟弟死在一起。

元忠每次迎来新的同伴，心中都会泛起一丝小小的羡慕。自己之所以决心赴死，是接受了武士无法避免的命运的结果。但是，他感觉这些人不一样。他们难道不是为了自己珍视的事物、为了自己的信念而选择赴死的吗？他们比自己更有勇气，也纯粹得多。至少，这些男人没有那种想要留名千古的算计。究竟怎样才能抵达他们所拥有的那个澄澈的世界呢？显然，学识教养或是世俗的地位，此刻都已毫无用处。

<p style="margin-bottom:3em;"></p>

二十日、二十一日都在枪炮交火中度过了。

二十二日，西军的主力部队抵达。元忠气喘吁吁地登上了天守阁。

城东南高高竖立着宇喜多家的剑片喰纹与儿文字纹大旌旗。东北方向，两枚巴纹友好地并排着。据说是右巴是小早川家，左三巴是毛利秀包。西北方向有岛津家的十字纹。虽说岛津家兵力似乎不足，但看来这支新到的部队人数应已过千。总之，那里是旌旗如林。那边可见锅岛家的旗帜，这边可见长宗我部家的旗帜。也有小西家的，还看到了安国寺家的。

元忠进一步转动视线。当目光扫过松之丸外的护城河时，他明白自己潜意识里在寻找的是什么了。那里，一面大书着“大一大万大吉”的旗帜，正在夏风中飘扬。元忠不自觉地露出了微笑。

虽然四万主力部队已经抵达，但战斗并未像元忠所期待的那样展开。那些能令士兵们疯狂、雄壮的军号与阵钲声，完全没有响起。传入耳中的，只有令人厌烦的枪声。元忠推测，大概宇喜多和石田都还没来吧。他们若在，攻城方不可能进行如此悠闲的战斗。

震耳欲聋的枪声，每到用餐时分便会戛然而止，突然的寂静随之降临。元忠最讨厌那一瞬间。安静下来，好不容易下定的决心便会动摇。

单凭枪击战是攻不下城池的。照这个势头坚守下去，说不定友军会赶来救援也未可知。虽然可能性微乎其微，但毕竟存在。一个已决心将伏见城作为墓地的人，到底在想些什么？元忠觉得自己太没出息了。

拜托快点做个了结吧。总之，别再让我东想西想了——

就是这样的心情。

然而，不凑巧的是，第二天、再下一天，战斗始终仅限于枪击战。唯独用来思考的时间，却多得令人厌烦。

元忠姑且算是净土宗的信徒。他深受佛教的吸引，却从未深入钻研过教义，这或许是因为他的弟弟忠广。忠广在三河一向一揆中曾顽强反抗家康，让鸟居一族很长时间都抬不起头来。自那以后，元忠对于灵魂救赎之事，总是刻意表现出冷漠的态度。

然而，年过五十之后，他开始感到有些无法再这样下去了。每当遭遇盟友或至亲的死亡，总会有一阵狼狈袭来。不知该如何应对，这令他焦躁。那感觉，就像赤手空拳地迎战强敌。从那以后，元忠几乎从不放过聆听法谈的机会。表面上依旧摆出冷笑的姿态，内心却充满好奇。他按照自己的喜好，适当地选取了适合自己的生死观。无论是净土宗还是禅宗，都强烈地吸引着他的心。

元忠喜欢“空”这个观念。一切事物都在不息地变化流转，从一种形态转变为另一种形态。所有一切都是短暂的现象，是幻影。即便是巨大的岩石，在烈日曝晒、雨水冲刷之下，也会逐渐风化、碎裂，不知不觉间化作从指缝间滑落的雪白沙粒。元忠陶醉于这样一种想法：一切事物，都是预先注定要如此变化的。那么，此刻吹过伏见城松树枝梢的那阵微风，或许在遥远得令人眩晕的太古之时，便已预备好了。与那阵风一样，自己大概也是预先注定要死在此地吧。

那么，死后又会如何呢？被火化的尸骸或许会升上天空化作云，再变成温柔的雨。雨水滋润草原，洒落京都街巷。剩余的骨灰则散入虚空，或许归于混沌。也可能在某一天，重新聚合为一个生命体而复苏，又或许不会。

这样不也挺好吗——元忠试图这样去想。

正如四季轮回一样，生与死也在不断循环。或许，人类是以“生”这种形态经历短暂的生命，又以“死”这种形态经历漫长的“死亡”吧。生与死仅仅是形态上的差异。如果是这样，人类只珍惜生而厌恶死，岂不是非常奇怪的事情吗？

元忠有时也会这样想：死亡，或许归根结底，就如同刀身从刀鞘中拔出，灵魂从肉体中获得解放，飞向永恒的彼岸吧。倘若如此，那么死亡无非是一场壮阔的归乡。

然而，生死观说到底只是知识，与决心是两回事。元忠完全没有信心，单凭这样匆忙收集来的、程度有限的生死观，是否真能实现“归乡”。

啪啦啪啦的子弹飞来，在他脚边扬起小小的尘土。

“哎呀，又开火了吗？”

元忠慢吞吞地站起身来。

双方仅以枪击战这种奇特的战斗方式，终究持续到了三成到来的七月二十九日。

<p style="margin-bottom:3em;"></p>

三成这天突然出现在伏见，是为了督促石田队。正忙于准备进军美浓的佐和山城主，将三千兵力托付给高野越中和大山伯耆二人，让他们参加攻打伏见城。听闻西军如此不济，三成几乎要昏厥过去。

“整整十天，就只是枪击战吗？！”

三成立即以秀家的名义召集了诸将。

“以四万之众的大军，竟对一座兵力不足两千的城池久攻不下？”

说到这里，三成重重地哼了一声。“各位的武勇，原来就是这样的吗？”

诸侯们个个垂首不语。武勇关乎意气和体面，可以说是武将的立身之本。而三成却对此轻加嘲讽。这是莫大的屈辱。更何况对方是那个瘦骨嶙峋的治部少辅，大家实在不愿意被三成说教何为武勇。

诸侯们像是被火烧了裸露的神经般，飞奔回各自阵营。然而，内心深处却又莫名感到一丝解脱。

主将首先必须是一个拥有强烈意志的存在。他根本不需要受到士兵爱戴。即使被憎恨、被畏惧，也完全无妨。仅仅是他出现在战场上，甚至仅仅嗅到他的气息，全军就必须为之振奋，不自觉地想要盲目地向敌人发起突击——必须是这样一种存在。从这个意义上说，能被称为有资格的主将的人，只有一个。这一夜，诸侯们重新、深切地认识到，西军的真正统帅究竟是谁。为了辉元，为了秀家，我们可不想去死。但是，若是在治部少辅的马前，嗯，倒也不是不能忍受——就是这样的心情。

局面变得有些奇妙。

<p style="margin-bottom:3em;"></p>

二十九日夜，各阵营的巨大篝火中，再次被投进了新的松明。似乎有什么东西和昨天之前不同了。包围伏见城的每一个人，都用自己的肌肤感受到了这一点。

下一刻，攻击几乎在全线同时展开。士兵们丢开枪炮，呐喊着冲向城门。即使岩石从头顶落下，即使热砂迎面泼来，他们也毫不畏惧。到处都是震天响的阵太鼓，阵钲如同发疯般鸣响。

翌日，七月晦日，诸侯们也没有放松攻击。仅仅这一天，总攻就多达四次，那足以令天地昏暗的枪声，一直传到了京都。

八月一日凌晨零时，松之丸毫无征兆地燃起了火头。

<p style="margin-bottom:3em;"></p>

是甲贺忍者倒戈了。甲贺一族被岩间兵库等人带领入城之事，前文已提及，而这最终成了伏见城的致命伤。

内应的部署，是由水口城主长束正家安排的。水口是甲贺郡的首府。正家家臣中，自然有不少甲贺出身者，以鹈饲藤助为首。正家利用这个藤助，向甲贺众时常出没的松之丸内庭射入了一封箭书。内容是：若执意敌对，便将你们在乡里的妻小抓来处以磔刑。但如果倒戈，在城中放火，则不仅保全你们妻小的性命，还会给予巨额赏赐。

箭书幸运地被甲贺出身的山口宗助拾到。宗助大受震动。不仅入城的人数，甚至连他们的名字都已泄露。逃也无处逃，藏也无处藏。宗助等人屈服于这番威胁，承诺内应。甲贺众在松之丸放火的同时，将城墙破坏了一百五十米，逃到了城外。

从松之丸燃起的火势蔓延到了名古屋丸。攻城方的士气顿时高涨起来。长束军率先开始进击，锅岛军、小早川军、相良军紧随其后。攻城者们打入鸢嘴钩，吆喝着攀上了石墙。

就这样，继松之丸、名古屋丸之后，治部少丸也被攻占。

负责防守追手口的松平近正赶去支援名古屋丸，在那里战死。三之丸守将松平家忠与蜂拥而至的岛津军激战三次，最终被义弘的家臣别所下野取走了首级。西之丸的内藤家长射杀了五六名闯入的敌人，但自己也身中箭伤，登上旁边的钟楼切腹自尽。家长十六岁的次男小市郎，在父亲战死时，正与攻城方的垣见一直交战。他稍松一口气，想起要和父亲一起切腹的约定，便来到约定的钟楼一看，楼已喷吐着火焰。少年将刀刺入腹部，冲入了烈火之中。

<p style="margin-bottom:3em;"></p>

八月一日上午十时，德川方的死者已远超千人，鸟居队也已减员至两百人。西之丸、二之丸也在熊熊燃烧，冒出滚滚浓烟。敌军涌入本丸只是时间问题了。

“打开城门。”元忠命令道。

若退守本丸，或许还能再坚持几个小时。但他不想被活活烧死。

两百名部下向着从干涸的护城河攻上来的石田队发起了突击。虽然是不成规模的突击，但元忠还是奋战了五次。每次出击，手下的兵力都在切实减少。副将笹山彦十郎未能归来，等他察觉时，自己身上也已受了十多处伤。

终于，接下来就是最后的收场了——元忠想道。十三天的笼城，已尽到了作为守将的义务。接下来只需考虑自己的名誉就行了，这对元忠来说是值得庆幸的。

对于频频劝说他切腹的家臣，元忠以可怕的眼神瞪了回去。若在尚有百名部下时切腹，那将是功亏一篑之举。

元忠又两次率众突出，再令人关上栅门。麾下兵力已减至十余人。疲惫感让身体仿佛要被大地吸进去一般。

元忠背靠石墙，仰望天空。漆黑的浓烟形成厚厚的云层，在低得惊人的空中向西飘移。

到这一步，应该可以了吧——元忠想道。当然，就算有人要求他再战，他也没有举起长枪的力气了。

“哈哈……”

元忠笑了。自己竟如此兴致高昂，这让他觉得有些滑稽。没能留下格调高绝的辞世句，事到如今也觉得不那么在意了。虽然没能用言语很好地表达，但他有种切实的感受：自己是用身体书写了辞世诗。

“能不能快点来呢。”

元忠有些费力地回头望向栅门附近。他完全没有切腹的念头，也不想被有名的武士讨取。

元忠在寄给长子新太郎的书信中，有这样一段话：

>“即便我死于足轻杂兵之手，身后之名遗臭天下，亦不以为耻。”

岂止不以为耻，被无名小卒砍下首级，曾是他隐秘的梦想。

<p style="margin-bottom:2em;"></p>

终于，栅门被打破，数百名武士轰然涌入。元忠一屁股坐在地上，双腿前伸，看着这一幕。

耳朵早已听不见了。冲在最前面的男子，似乎在大声吼叫着什么。能看到他上吊的眼睛和血红的嘴巴。

下一刻，一股巨大的力量，将元忠猛地向后推去。
