# 第六十一章 彦兵卫之城 {-}

翌日八月九日，朝日初升之时，石田军六千人马浩浩荡荡地开出佐和山。三成将留守事务托付给父亲正继与兄长正澄，在城中留下二千八百兵士防守，人数不少，但其中多为老人与文官。

三成一行人穿过侍从宅邸林立的大洞一带，向马苦劳町、新町、鱼町进发。先锋的荣誉此日由岛左近胜猛担当。岛队之后，蒲生备中、小川平左卫门、新藤缝殿、后藤又介、百百宫内、早崎平藏、分田伊织、浅井新六等诸队三千七百人相继跟随。三成与亲卫队三百人随后到来。道路两侧挤满的领民欢呼声骤然高涨。

这位不受欢迎的奉行，在领民中却颇受爱戴。像三成这样公平征收租税、尽心于防灾备荒、致力于工商业发展的大名实属不多。“治部少辅的近江”甚至曾被诸侯们奉为领国统治的一个典范。据说这个早晨，领民中甚至有感动至极而哭泣者。三成显得非常难为情。

第二队的大将由蒲生乡舍担任。蒲生队之后是中岛宗左卫门与大场土佐，再往后是大山伯耆等诸队。这边人数为二千。

石田军在午前稍早时分已越过近江与美浓的边境。从此处到今日的宿营地——垂井，距离彦兵卫的城池仅仅十五公里。

“到达垂井后，必须立刻派遣使者。”

三成在马上不时挺起身子，屡次偷偷向东张望。

<p style="margin-bottom:3em;"></p>

恰在此时，大垣城内，一名中年男子正在四层天守阁的最高层不安地来回踱步。他便是城主伊藤彦兵卫。彦兵卫时而回首望向垂井方向，发出沉重的叹息。石田军进驻垂井的消息，不可能不震动美浓的诸城。这无异于向在这片丰饶大地上筑城的二十二位不可大意的男儿亮出匕首，迫使他们重新做出向西还是向东的选择。二十二人中，有十七人暂且表示了欢迎之意。彦兵卫也暂且置身其中。

然而，彦兵卫忧心忡忡。西军胜也好，东军胜也罢，对此人而言并非什么大不了的问题，他忧虑的是大垣城本身。彦兵卫十分清楚自家城池在浓尾平原中所占据的重要性，害怕三成会开口向他借城。这不是杞人忧天，大垣城不仅三面皆不容敌军兵马侵入，更有着一种足以激励那些志在平定浓尾的野心家的、充满魅力的特质。

大垣城的背面是关原的山峡。北侧是自伊吹山脉延伸而来、如屏风般连绵的巍峨山块，南侧则是延绵至伊势、伊贺的铃鹿山脉。彦兵卫将目光转向东方，唯有那里充满了明快的色彩，没有任何东西妨碍观景。绿色的沃野以他此刻站立的大垣城为扇轴，呈扇形扩展，极目远眺，大地一直延伸到没入伊势湾的海岸。就连在平原上蜿蜒流淌的揖斐川、长良川、木曾川这三大河川，也仿佛是为了守护此城、衬托其壮美与坚固而存在的。

得益于此，这位仅有三万四千石的小大名每次登上天守阁，总能沉醉于一种仿佛自己成了这广阔平原真正主宰者的幸福错觉中。然而，在三成进军美浓的这一天，眼下的风光却丝毫未能慰藉这个胆小又爱虚荣的人物。涌上心头的尽是忧虑。

“像治部少辅那样的人物，难道会察觉不到大垣城的重要性吗？”

彦兵卫再次回到了最初的命题。

美浓若是连城砦也算上，城池多不胜数。最大的是岐阜城，但三成不太可能进入那里。无论多么傲慢的奉行，面对信长的嫡孙，恐怕也难以轻易说出“暂借贵城”这样的话吧。既然如此，三成也不会进入犬山城或竹鼻城。

木曾川河岸上几乎等距矗立的那三座城，可谓大坂方面的防线。治部少辅需要一座指挥城池，像御者驾驭马匹那样，能够拉紧或放松缰绳，以督励和节制那三城——这样一座位于更后方的城池应该是必需的。

“那就是我的大垣城。”彦兵卫想道。无论考虑多少次，得出的结论都一样。

“不。”彦兵卫闭上了眼睛。“唯有这件事，我定要拒绝。”

<p style="margin-bottom:3em;"></p>

伊藤一族对于那座城，似乎确实拥有足以拒绝的权利。

彦兵卫的父亲盛景，原为美浓舟冈城主，因小田原之役的功勋，于天正十八年获赐大垣三万石。当时的大垣城只是仅有本丸、二之丸、三之丸的小城，父子俩立刻着手城郭的改建，增建天神丸、竹之丸、松之丸、袋丸等诸郭，耗费了大约九年的岁月。父亲盛景已于前年辞去官职，这座堪称一族唯一财产的城池，由他彦兵卫继承，此时，改建工程也终于接近尾声，
六百米见方的郭内，排列着十五座橹和二十六座渡橹，其协调之美，就连近邻那些嫉妒心强的大名见了也会为之陶醉。

然而彦兵卫并不满足。他几乎总是在让人修整某处。哪怕白墙稍有污迹，洁净的郭内掉落一片垃圾，彦兵卫也会露出仿佛胃疼难忍的表情。除了将城装扮得更美，他别无任何嗜好。彦兵卫没有纳侧室。感觉就像是已被“城”这个恶女迫使耗费了大量钱财，实在无暇顾及其他。

彦兵卫此人是个执着成性的人。他曾八度改名，或许也证明了他会有这种偏执的癖好。但是，近邻的大名们谁也不称他为“盛正公”或“盛宗公”。首先，“盛宗公”就毫无感觉可言。大垣城的主人必须是彦兵卫。只有在称呼“彦兵卫”时，邻居们才能从心底切实感受到对这个仿佛被城吸走了魂魄的怪人的些许轻蔑与同情。

<p style="margin-bottom:3em;"></p>

然而，从本故事的时间点大约五十天后，他们将被迫急急忙忙地修正对彦兵卫的认识。他并不仅仅是将城装饰得漂亮而已，完全出人意料的是，事实证明彦兵卫具有作为筑城家的才能。

关原决战之日，东军的水野胜成、松平康长等诸部队如怒涛般涌向彦兵卫的城池，但以福原长尧为守将的西军轻易将其击退。简直像在说：要不你们再来一次？

但随着西军的败北，情况为之一变。理所当然地，背叛开始了。十七日，相良赖房、秋月种长、高桥元种三名守将谋杀了熊谷直盛、垣见一直、木村由信、木村丰统，将其首级献给井伊直政，并同时将东军引入二之丸和三之丸。他们不仅引入东军，还与东军联手攻击昨日的同伴。

但是，仅由福原长尧一人防守的本丸却未被攻陷。翌日十八日、十九日连续进攻，依旧岿然不动。大垣城是建于平地的平城，而且二之丸、三之丸已然陷落。这在通常情况下是难以想象的。

攻城第十日，长尧终于开城。并非被攻陷，而是因家康恼怒而派来的禅僧的说服起了作用。

倘若福原长尧坚持固守，彦兵卫之城或许一年也不会陷落吧——邻居们极其热心地如此议论，仿佛在说服自己相信一般。

大垣城就是如此的名城。大垣城作为西军大本营的这大约五十天里，日本的历史仿佛正是围绕着彦兵卫之城在旋转。

<p style="margin-bottom:3em;"></p>

总之，在三成现身美浓的这一天，彦兵卫的内心持续剧烈动摇着。

刚想着他会说“与其借城……”之类的话，同一张嘴却又脱口而出“若是连此城的好处都看不明白，治部少辅也算不上什么了不起的人物嘛”。借城是绝对不愿意的。但即便如此，彦兵卫又无论如何都希望对方能认可此城的重要性与出色之处——此人正陷于这种极其矛盾的心境之中。这有点类似一个迫于生计必须卖掉自己精心栽培的盆景的人，对顾客所抱有的感情。假如三成对大垣城不屑一顾，径直路过的话，彦兵卫想必会因此大感不快。

这天夜里，彦兵卫将两位重臣——伊藤赖母与同伊予唤入自己的居室，密谈了一个小时左右。而他的重臣们似乎证明了自己并非白拿那么高的俸禄。

翌日早晨，三成的使者叩响了彦兵卫之城的城门。年轻的使者在前往书院的途中，时而触摸柱子，时而重重踩踏地板。

“早有耳闻，真是座好城啊。”使者说道。

感觉并非只是客套话。唯有此刻，彦兵卫对这个必定是来夺取自己珍贵城池的年轻男子，产生了一丝类似好感的情绪。

“不过是个乡间小城罢了。”

“您太谦虚了。无论是城的布局还是用料，如此出色的城池，在美浓也不多见吧？”

“哪里哪里。”

使者越是赞美，彦兵卫的回答就越是简短冷淡。

“愿闻贵使来意。”

“是的是的，首先得把这事办妥。”

使者重新坐正。

彦兵卫处在一种奇妙的陶醉感中，听着使者转达三成的口信。他曾经对这一刻恐惧得要死。但此时彦兵卫感到的却是安心，非常安心。

“也就是说，是要我把城借出来吧？”

“一切都是为了秀赖公。”使者答道。彦兵卫仿佛能看见三成那张脸似乎在说：为了秀赖公，借一两座城不是理所当然的吗？

“有一事想请教。”

“请讲。”

“倘若借出城池，我们究竟该去往何处呢？”

“哪里都可以。”

“这可真是，相当过分的说法啊。”

彦兵卫勃然大怒。他心想，值此天下动荡之际，也请体谅一下我方被迫离城、驻扎在无壕无防之处的处境。

“我拒绝。”彦兵卫说道。

“还请您不要事后后悔。”使者突然站起，似乎把彦兵卫当成了东军一伙。

面对这仓促的结束，彦兵卫反而惊慌起来。

“虽则如此回绝，”彦兵卫追赶着走向玄关的使者，“但并非是要与内府为伍。我方也有种种情由。恳请将在下的苦衷，仔细转达给治部少辅。”

“那家伙，生气回去了啊。”

“请您不必担心。”老臣伊藤赖母从主人背上拈起一点灰尘。

“他不会立刻就来进攻吧？”

“啊哈哈……”老人张开没牙的嘴笑了。

“你确信他必定会再派使者来，是吧？”

“我向神明发誓，他们会的。”

“然后我们这次要接受提议，是吧？”

“正是。最好是显得心有不甘的那种感觉。”

“既然终究要借，为何要多费这番周折？”

“若不如此，大坂方战败之时，我们便无法向内府做出解释了吧？”

“赖母，你喜欢内府吗？”

“不不。在下只喜欢胜者。在下从不挑拣对手。”

“你这讨厌的老头。”

<p style="margin-bottom:3em;"></p>

后来的发展，大体上顺着这个讨厌老头的算计展开了。彦兵卫被三成再次派来的使者那充满真情的说服打动，心不甘情不愿地带着城兵移往领地内的今村之里，在那里挖掘壕沟，匆忙建起类似城砦的设施。取而代之的，八月十一日，三成进入了彦兵卫之城。

<p style="margin-bottom:3em;"></p>

且容我们将彦兵卫的故事继续讲完。虽说借出了城，彦兵卫却似乎是个啰嗦的房东。他不出三天便会来大垣，对城的使用方法提出各种要求，惹得三成厌烦。

最终，彦兵卫家未能在下一个时代存活下来。邻居们议论纷纷：

“他把城借出去，触怒了内府。”

也有人说： “他奉命去援救福束城的丸毛三郎兵卫，结果反倒要了自己的命。”

关原之战后，彦兵卫逃往加贺，以二千石俸禄侍奉前田利长。在彦兵卫前后，另有一名美浓小大名也出仕了前田家。那竟是促成伊藤家没落的原因之一——福束城主丸毛三郎兵卫。此人的家禄正好也是二千石。

遗憾的是，二人在加贺度过了怎样的下半生，没有任何记载流传下来。

