# 第六十四章 花 {-}

在伊势国，还有另一位画下奇妙轨迹的大名。

那就是桑名两万五千石的大名·氏家内膳正行广。行广有个弟弟志摩守行继，此人在伊势和近江境内也领受了一万五千石的俸禄。他们只是两个小大名，但是，对于得到桑名这块土地的兄弟俩，没有哪个诸侯不羡慕他们的幸运。

桑名是一座在木曾川、长良川、揖斐川三大河与伊势湾连接的河口处发展起来的商业城市。上游的美浓、飞驒收获的大米和木材等各种物资都先集中到桑名，然后从这里经由海路运往大坂等大的消费地。因此，桑名自古以来从事运输业的人就很多，像山田彦左卫门那样一代发迹的商人也不在少数。

桑名还是东海道最大的驿站。在那个时代，前往关东的旅人通常是从四日市经陆路进入桑名，然后从这里利用船只前往尾张的热田神宫。这就是所谓的“七里渡口”。理所当然地，为了等待乘船的旅行者，这里建起了大量的旅店，周边也聚集来提供一夜欢愉的女性。她们被称为“二朱女郎”。

而且，桑名还是一个大渔港。城镇里总是弥漫着富裕的气息和一种近乎猥亵的活力。桑名从室町时代起就被称为“十乐之津”，这并非没有缘由。

桑名本是关白秀次的领地，行广被赐予此地是在秀次失势的文禄四年。太阁之所以将这片诸侯垂涎的土地，赐给父亲是美浓地侍出身的行广，或许与他父亲的死不无关系。

<p style="margin-bottom:3em;"></p>

元龟二年（1571），隶属柴田胜家队、进攻长岛愿证寺的氏家卜全，在撤退战中主动要求殿后，在石津郡太田村壮烈战死。而桑名曾是长岛领地的一部分，当年丰臣秀次将天守阁从伊势的神户移筑过来，在此建起了桑名城。太阁对这种表现忠诚的行为毫无抵抗力，将父亲卜全的殒命之地赐给了氏家兄弟俩。


当时出现了一个巧妙的传言，说太阁之所以把桑名给行广，是因为宠妃淀殿的央求。确实，淀殿和行广之间似乎存在某种联系。行广的妻子是京极兄弟的妹妹，也就是淀殿的表姐妹。而且行广在兄长左京亮突然去世而继承家业之前，曾作为太阁的近臣在大坂生活了数年。但是，那种暗示两人之间存在暧昧恋情的轻浮流言，不久就平息了。因为行广那年已经五十岁了，而且他是罕见的这辈子与绯闻无缘的人物。

<p style="margin-bottom:3em;"></p>

关于氏家行广进入桑名，留下了一则有趣的轶事。

故事要追溯到天正十八年。这一年，行广为了参与小田原攻城战，与两位友人一同前往关东。一人是京极高次的弟弟高知，另一人是近江朽木谷的领主朽木元纲。

一行人那晚投宿在近江草津的客栈，办了个小酒宴。期间，客栈主人出来打招呼。朽木元纲叫住他，开玩笑说：“你来猜猜看，我们三人之中，将来最有出息的是哪一个？”

这么看来，这位客栈主人或许因擅长相面而颇有名气。

主人连连推辞，但不久就像下定了决心似的，指向了行广。

“目前，桑名没有城主。在不久的将来，您必定会得到关白的青睐，成为那座城池的主人。”

预言应验了。主人像是迫不及待地等着行广入城似的，前来桑名表达“新入城的贺仪”。这种时候，按理应该备上厚礼的。

但是，新领主辜负了主人暗自的期待，只给了相当于普通贺礼程度的回赠物品。对于近臣们疑惑主人为何一反常态的吝啬，据说行广是这样回答的：

“他那启程前的一番话，不过是偶然言中罢了。若是给这种瞎猫碰上死耗子的预言巨额奖赏，那对于从父亲、兄长时代起就有功于本家的家臣们，又该拿什么来回报呢？我如此轻待他，正是为此。不过，想想看，与那位客栈主人的缘分也算奇妙。今后每次往返京都一带时，就使用那家客栈好了。”

能窥见他为人处世的轶事仅此一件。历史上的行广似乎是个非常内向、在武人当中属于性格非常温和的人。

<p style="margin-bottom:3em;"></p>

七月下旬，氏家兄弟率领千余士兵，从桑名出发。当然，是为了跟随家康征讨会津。上个月，返回江户的家康一行不知为何绕开桑名，从四日市乘船出发，这件事虽然留下了一点小小的隔阂，但会津动员令毕竟是以丰臣政权的名义发出的。

氏家队扬起白色的尘土，沿着东海道北上。行进到滨松附近时，三成举兵的传言追上了他们，随即又更快地向北传去。

行广垂着头，呆立在街道上。三成也同样打着“为了秀赖殿下”的旗号。究竟该相信谁呢？

最终，行广还是下令折返桑名，那是七月二十七日的事。

对兄长这突如其来的决定感到最震惊的，是弟弟行继。兄弟俩的性格和体型都不太相似。行广是理想主义者，有些古怪之处；而弟弟则是个典型的乐天派。行继被所有人喜爱，甚至家康也不例外。

兄弟俩回到了桑名。但是，令行继感到意外和不满的是，兄长完全没有派遣使者前往大坂的迹象。回到居城的行广似乎心事重重，只是每天在城内散步度日。行广原本就有这种沉思的习惯，但回城后似乎愈发严重了。

“那么，”行继用极为轻松的口吻对兄长说道，“派往大坂的使者，您已经决定了吗？”

“大坂？有这个必要吗？”

“既然决定要加入我方，不是应该尽快表明心意吗？”

“我并没有决定要加入治部少辅一方。太阁殿下死后，治部少辅对内府所展现的专横感到愤怒，这心情我理解。但即便如此，我也不想拥戴他。”

“您这话的意思……”

“内府再怎么碍眼，动用兵马也应该等到秀赖殿下成年之后吧？”

“可是治部少辅已经举兵了。”

“喜欢的话随他去打好了。”这是一种极为冷漠、甚至带点恶意的说法。

“那我们氏家呢？”

“遵从良心。”

说实话，行继不太明白兄长所说的“良心”究竟指什么。或许兄长从三成的举兵中，也感受到了某种刺激神经的不纯动机吧。

“这不是会同时被石田和德川两方面都记恨吗？”

“大概是吧。”

只有那一刻，行广露出了有些胃疼的表情。

桑名城主公平地赶走了东西两阵营派来的使者。

“很抱歉，我无意加入任何一方。”

行广对最先来访的三成家臣·武家佐兵卫说道。

“也就是说，保持中立吗？”

使者的脸上瞬间闪过一丝嘲讽。毫无疑问，佐兵卫将兄长的话理解为了“骑墙观望”。

“您怎么想是使者大人的自由。我只说一句：我绝不会做出暗中通敌关东、悄悄把马拴在内府门前的卑劣行径。”

大约半个月后，这次是本多忠胜的某位家臣，趾高气扬地来到了桑名。使者说道：

“内府对您内膳正大人的决断感到非常高兴。”

看来行广赶走三成使者的消息也传到了江户，家康听说后似乎立刻就想派使者过来。

但是，这一次行广的拒绝也同样冷淡。

“我曾受太阁殿下眷顾。因此，无法参与任何可能导致丰臣家灭亡的战斗。如果再次派遣使者前来，虽然很遗憾，但我将不得不斩下使者的首级。希望你能这样转告内府。”

声音平静，不带情绪，但行继却感到一阵寒栗。以兄长的性格，他真有可能砍下人头。

<p style="margin-bottom:3em;"></p>

然而，行广终究未能将中立坚持到底。率兵进入伊势的宇喜多秀家，不是那种会容忍这种暧昧态度的人物。兄弟俩被强行拉入西军，与隔着一条河的东军福岛正赖对峙着迎来了战争结束。

关原的捷报传来同时，正赖便调动兵力包围了桑名城。但行广并未特别下令防御。一副“随便你们怎么处置”的样子。

无可奈何之下，町年寄伊藤武左卫门多次往返于正赖之间，商定了和谈条件。这简直是场闹剧。最终，桑名城无血开城。

战后，家康暂时将行广驱逐到高野山，随后委托池田辉政和京极高次赡养这位前桑名城主。家康明白行广并非自愿加入大坂一方，但若将这位被列为西军一员的人物继续留在诸侯之位，社会舆论不会允许。

弟弟行继则被交由细川家看管。即使在那里，他也发挥出与生俱来的魅力，成为领受三千石俸禄的重臣，他的一位女儿还嫁给了细川忠兴的次子——曾一度被视为细川家继承人的兴秋——为妻。

<p style="margin-bottom:3em;"></p>

从那以后，行广便与两个儿子左近、内记一起，在池田、京极两家的新领地播磨和若狭之间来回迁徙，度着岁月。他也时常会远足到丹后的田边城。曾在草津的客栈一同聆听主人预言的旧友高知，因关原之战功，在丹后受封了十二万三千石。

随着年龄增长，行广变得更加沉默寡言。父亲在想什么，两个儿子也无从知晓。

<p style="margin-bottom:3em;"></p>

庆长十九年，关东与大坂的形势变得不稳。家康忽然想起了这位前桑名城主。

十四年的岁月，将取代太阁的新独裁者，变成了一位多愁善感、极易冲动的老人。老人怀念起逝去的时光。过去的一切都显得美好而珍贵。今天发生的事会忘记，但几十年前的记忆却惊人地清晰，甚至能想起每个细节。

同辈的武将大多已入鬼籍，剩下的只有自己和行广了。家康甚至能想象出两人在透着微光的房间里，相对而坐的景象。当初根本没必要剥光氏家的领地。老人如今幡然悔悟，莫名地想伸出援助之手。

听到氏家卜全战死时，太阁被一种无论如何也要帮帮他遗孤的冲动所攫获；如今，同样的冲动跨越了数十年的岁月，攫住了家康。老人想：让那个人重新出仕吧。

幸运的是，大坂冬之阵即将开始。并不需要他建立什么功勋。只要氏家行广表示站在德川一方，对家康来说就足够了。

<p style="margin-bottom:2em;"></p>

老人急忙派遣使者前往行广处。使者对这位前桑名城主的衰老深感震惊。皮肤失去了光泽，花白的头发只剩勉强能扎起的量。上排牙齿全部脱落，下排也仅剩两三颗泛黄的牙齿。或许是因为缺牙，嘴角下垂呈“へ”字形，这让行广看起来更像个脾气乖戾的老人。使者实在无法理解，主人为何要让这样一个废物重新位列诸侯。

如果说老人的脸上还有哪部分保留着昔日的影子，那便是眼睛。只有眼睛逃脱了岁月的侵蚀，依然清澈得惊人。

听到使者的来意时，老人的眼中迅速掠过什么。使者无法确定那是不是喜悦，但无论是喜是悲，那无疑是极其强烈的感情。

老人张开了嘴。从脱落的齿缝间，断断续续地吐出“不肖之子”、“既已舍弃兵武之道”、“恳请见谅”之类的话语，伴随着大量的唾液。老人喘了口气，又开始说些什么。任其下去，似乎会永无止境地说个不停。

使者回去后如实禀报。

家康很失望，拿使者撒气。对方是个耳背的老人，连自己的好意是否准确传达都值得怀疑。

那个男人一向挺要面子的。或许是不愿连一个随从都不带，只身一身，就这样前往大坂吧。流放已达十四年之久。在此期间，家臣团离散的可能性很大——

家康这样想着，以此来安慰自己受伤的心。除此之外，真的想不到其他理由了，也有点不敢去想。

就这样，救助氏家成了家康的执念。

<p style="margin-bottom:2em;"></p>

翌年元和元年（1615），大坂夏之阵爆发。四月四日，家康从骏河出发之际，再次派遣使者前往当时寄食于丹后京极家的氏家行广处招揽。

家康的口信清晰得不容任何质疑。

“听好了，”家康对担任使者的年轻人一字一句地叮嘱道，“只需他来大坂，就赐予十万石。无需带一个随从。对，就在他耳边反复这样说。”

家康于十日进入名古屋城，在此停留了五天。

期间，家康屡次询问“使者还没回来吗？”，让近侍们感到诧异。第九子义直的婚礼就在两天后，但这种事无关紧要。老人更牵挂的是旧识的答复。

不知何时起，家康开始将这位前桑名城主的应允与否，视为衡量自己正义的试金石。他隐约觉得：如果行广肯前来相助，那么自己用奸计杀害太阁遗儿的行为，是否就能获得某种宽恕呢？

<p style="margin-bottom:2em;"></p>

最为旧友重获出仕机会而高兴的，莫过于京极高知了。

“您果然是个运气很强的人啊。十万石，真让人羡慕。要是草津的客栈主人还活着，真想让他再占卜一次，看看这回您能得到哪里呢。”高知如此说道。

行广跟随前往大坂的京极队一同离开丹后，两天后便已进入京都。

高知将旧友送到二条城附近。家康已于四月十八日进入二条城。告知大御所驻城的数十杆白旗，仿佛在招引行广似的，在晚春的天空中飘扬。

离别之时到了。两位老将头顶上，一棵开满无数鲜红花朵的巨大山茶树，枝桠伸展到了路上；眼前，一条白色的道路笔直延伸。花的红与叶的浓绿，刺眼般鲜明。

行广瞬间露出像是要哭出来的表情。高知对友人的退缩感到焦急。他抓住老人的手臂，让他朝向城池方向，有些不耐烦地推了推他单薄的背脊。

高知急忙离开，大步往回走。走了一会儿回头一看，老人还站在原处。高知烦躁地挥了挥右手，像是在驱赶一只老跟着主人的狗。

高知转过头去，再也没有回头。

<p style="margin-bottom:3em;"></p>

大约十天后，高知从家康的近侍那里得知，旧友仍未进入二条城。但他没有去若狭自己家，也不在播磨的池田家。

“究竟，他是怎么打算的呢？”

使者年轻人一副完全不知所措的样子。那语气仿佛在诅咒自己的不幸，被命令去寻找一个毫无用处的老人，而战国最后的决战却迫在眉睫。

送走近侍后，高知前往隔壁的阵屋，拜访兄长的儿子忠高。高知的兄长高次于庆长十四年去世，若狭京极家已到了他儿子这一代。在夏之阵中，他将与二十三岁的侄子一同奉命防守“野江之堤”。旁边是忠高队，背后是石川主殿头队。

叔父与侄子走出阵屋，信步向一个方向走去。眼前，近得惊人之处，便是即将攻打的太阪城。

听到行广突然失踪的消息，忠高也并未特别惊讶。

“消失了？真是个让人不省心的人。那个人从以前起就完全让人捉摸不透。总之，是不是就是不想当大名呢？”

他用冷淡的口吻这样说道，又小声补充了一句。

“明明照顾了他十五年。看来帮人也没什么好处啊。”

侄子的语气惊人地像他哥哥。

<p style="margin-bottom:2em;"></p>

战斗于五月六日开始，仅持续三天便结束了。京极一族从野江向片原町进军，侄子斩获敌首三百七十级，高知斩获三百零二级。合计六百零九级，仅次于藤堂高虎的八百六十七级，位列第二。也就是说，为了诛杀近亲淀殿及其子，京极一族立下了诸侯中第二的战功。

五月八日正午，高知缓缓地在堤上漫步，仿佛在确认脚下的路。那时，他感到一种奇妙的违和感。总觉得有些不对劲。下一瞬间，高知“啊”的一声回过头。然而，那里已没有早晚看惯了的天守阁。

“丰臣家没了。”

丰臣氏灭亡的事实，从未像那一刻那样，如此真切地迫近他。

<p style="margin-bottom:3em;"></p>

而就在这一天，高知听到了一个让他简直怀疑自己耳朵的传言。据说在殉死的二十八人中，有一位自称荻野道喜的老武士。道喜是行广的法号。

高知感到一阵厌恶。那个老武士何时进入大坂城，受到过何种待遇，完全不得而知。只知道他参加了当天激战最烈的天王寺口的战斗，在我方败退后返回大坂城，为避难于山里曲轮的粮仓中的淀殿介错，然后仿佛叠在其尸体上般自尽了。

殉死者的身份，稍后以更清晰的轮廓传到了野江。二十八人中，有二十五人查明了身份。在大野治长、速水守久、毛利胜永、真田大助、韩长老、大藏卿、饴屋局、宫内卿这些熟悉而华丽的名字背后，仿佛隐身般地，混杂着荻野道喜的名字。

据幸存者证言，道喜毫无疑问就是氏家内膳正行广。行广或许是害怕连累亲属，才改了名字。

侄子忠高的慌乱到了令人怜悯的地步。

“但愿别引起什么奇怪的猜疑才好……”

忠高一边说着，一边不停地擦汗。他似乎最害怕行广的事会牵连到作为保护者的自己头上。

<p style="margin-bottom:2em;"></p>

与侄子分开后，高知信步朝自己的阵地走去。途中有一条水渠。树荫令人倍感舒适。高知像是松了口气般坐了下来。回过神来，发现自己正在无声地哭泣。并非因为旧友之死而悲伤。即便给予多么优厚的照顾，年过七十的老人，也不觉得他还能活多少年。

那时攫住高知的，是对人类精神的赞叹之情。

说实话，他不甚明白旧友为何要殉于丰臣家。报数十年前太阁之恩是最普遍的说法，但高知觉得这种想法多少有些牵强。将报恩之类不纯的动机带入旧友的死，未免可笑。行将就木的老人，或许只是单纯地将大坂城选为合适的葬身之地罢了。

无论理由是什么，高知觉得这种死法是壮丽的。壮丽，是他最真实的感受。

高知的呜咽声突然止住了。那时，他注意到眼前，有什么红色的、巨大的东西，漂浮着顺流而下。

是山茶花。即使眺望上游，也看不到像样的树木，但拥有深暗红色、如同蜡制工艺品般的花瓣，却接连不断地漂来。而后，它们突兀地中断了。

高知下意识地等待着下一波。愿望不久便实现了。这次的花朵比之前的更大，足有少年头颅大小。或许因为漂来的只有一朵，总之在他看来就是那样。那朵花枕着流水悠然而来，甚至带有这般风致。

山茶花被水流戏弄着，在他面前滴溜溜地打转。高知莫名地仿佛听到了旧友的笑声。这朵厚重的山茶花一点也不像衰老的行广，但它终究正是那位前桑名城主的化身。似乎舍不得与这朵山茶花告别，高知气喘吁吁地沿着水渠边的小路跑了起来。

<p style="margin-bottom:3em;"></p>

像家康那样听到氏家行广临终消息时那样可怜的人，大概找不出第二个。

行广的死，不仅是对德川政权的正当性，更是对家康的人性，进行了无声的控诉。家康懊悔不已，恨对方已死。他心想，若是活着，定要将其碎尸万段。但是，要让这份控诉撤回去，是绝对不可能了。

家康下令逮捕行广的遗儿。

死刑于五月二十九日，在京都的妙觉寺执行。行广有四个儿子。长子左近、次子内记，以及在流浪期间生下的三子和四子八丸。三子的名字未能流传下来，或许是因为他早早成为了比叡山南光坊天海的弟子。只有这个三子，由于天海的竭力哀求而免于一死。

兄弟几人被带入围栏中，从左到右按年龄顺序排列。预定时刻到来时，左近对最小的弟弟说道：

“小八，你能不能先切腹？”

八丸才九岁。左近是担心小弟弟会出丑。

“这倒可以……不过……”八丸欲言又止。

“有什么担心的吗？”

“我还没见过人切腹，不知道该怎么做。请哥哥您先做个示范吧。”

“也是哦。”左近微微一笑。“那就哥哥先切。你照着做就行。”

左近和内记褪下上衣露出肩膀，在腹部横向切开一道口子。两位兄长的首级就落在了注视着这一切的孩童眼前。

八丸似乎彻底放心了。少年挺起胸膛，敞开腹部。

就在此时，聚集在妙觉寺围观的群众中，发出了惊叫声。目睹斩首的京都医师斋藤玄可在日记中这样记录当时的情景：

“观者无论老少，皆不忍直视，放声哭泣，奔出门外。”

