# 第六十七章 劫 {-}

在清洲城的大广间里，连日来将领们都在举行着军议。十八日，福岛正则终于怒吼道：

"内府是打算把我们当成劫材来使吗！"

所谓"劫材"，就是围棋中暂时舍弃的一部分棋子，故意让对方吃掉。正则破口大骂，说家康打算抛弃他们，让他们成为西军的饵食。

池田辉政听到这话，便站出来为岳父辩护：

"太夫，说话谨慎些。内府不是会做那种事的人。"

但没有人支持辉政。

不只是正则。客将们都是从心底里窝着火。先锋部队进入清洲已经快七天了，可答应好马上就会追上来的家康，却至今不见踪影。

到达的头一两天，客将们还兴致勃勃地参观闻名已久的清洲城。清州城的面积很大，东西约一公里半，南北约二点七公里，大约是彦兵卫城池的三倍。三层四阶的天守围着黑色的护墙板，最上层环绕着朱红色的栏杆。黑与红的对比，令人印象深刻。

而最重要的是，这里充满了战国历史的气息。不，这里就是历史本身。织田信长从桶狭间出击时，曾在这里舞《敦盛》；信长死后，柴田胜家在这里主持召开"清洲会议"；两年后，直面长久手之战的织田信雄与德川家康在这里运筹帷幄——都是这座城。正则的这座城，曾三度深刻参与战国霸者的选拔。

<p style="margin-bottom:3em;"></p>

然而，参观完城池之后就不行了。客将们不知谁起的头，聚集到正则的居室，开始起劲地说家康的坏话。这里没有辉政，也没有家康作为自己代表随同西上军出发的两位军监——本多忠胜和井伊直政。坏话可以说得肆无忌惮。

"内府太迟钝了。和太阁殿下根本不是一个级别的。"

客将们仿佛现在才想起来似的，怀念起秀吉的"中国大返还"。

据《川角太阁记》记载，就连平时谨慎的细川忠兴也曾这样抱怨过：

"内府真是个疑心重的人啊，说不定比太阁的执念还要深十倍不止。真是让人受不了。"

甚至还有武将说：“内府该不会是根本没打算离开江户吧？”说这话的是冈崎的田中吉政。

没有人敢断言"不会吧"。家康经过深思熟虑后，有可能暂时搁置西征，转而专注于江户的防守，这是最自然的思路。

在此期间，进入大垣城的三成对东军的策反工作从未停止。三成谋略的手首先伸向了田中吉政和鸟取城主宫部长熙，接着又伸向了细川忠兴和福岛正则。三成的密信，就其本身而言，相当具有诱惑力。虽然没人老实承认自己和三成接触过，但从他们睡眼惺忪、深深思索的模样，大家也能看得出来，在这个时期，清洲的客将中，没有人是两眼清亮的。

<p style="margin-bottom:3em;"></p>

军议一天比一天气氛险恶。诸侯们毫不客气地责备着两位军监。每当这时，山内一丰的脸色就显得很难堪。因为根据一丰那著名的提议，东海道沿线的大名们全都把城池献给了家康。

家康毫不客气地派家臣跟随前往清洲的客将，接收了排列在东海道上的十三座城池。清洲城也派来了松平家清、石川康通两位家臣。所以正则只好避嫌，没有进入本丸，现在只能住在二之丸。

不只是城池，家康还不断征集人质，将他们送入辉政的吉田城。简直是巧取豪夺到家了。客将们对迟迟不露面的家康怒火中烧，也情有可原。

<p style="margin-bottom:2em;"></p>

陷入困境的军监们，连日向江户派出快马。忠胜和直政最害怕的，就是正则变心。家康的迟到，等于给了福岛正则一个夺取天下的绝佳机会。

简单来说，如果正则说出：

"既然内府不来就算了。咱们自己进攻治部少辅如何？"

那么，田中吉政自不必说，细川、加藤嘉明，甚至可能浅野也会兴高采烈地追随。这样一来，黑田长政说不定也会兴冲冲地从家康那边转投他的挚友。虽然可能性很小，但确实存在。

如果当时如水在清洲，他十有八九会毫不犹豫地投身夺取天下的大业吧。

但值得庆幸的是，清洲城主的脑子里，似乎从未浮现过夺取天下的野心。

<p style="margin-bottom:3em;"></p>

在江户——

家康一刻不停地、终日写信。当然，是为了笼络诸侯的心。自从小山评定以来，自己究竟写了多少封信，家康已经不记得了。一百封？不，或许已经超过一百二十封了。其中十三封是写给清洲城主的。甚至可以说，他满脑子想的都是正则。

在堆积如山的信件中，家康慷慨地许下了恩赏的承诺。

七月二十九日，他剥夺了增田长盛在伊势的领地，将其赐给了桑山元晴。这简直就像在开战前就"杀掉了"长盛。家康心想，管他呢。写信是一项相当耗费神经的孤独工作。如果没有杀掉一个看不顺眼的家伙当作慰藉，简直撑不下去——他怀着这样的心情。

八月十二日，他又"杀掉了"小出吉政和小西行长，许诺将但马一国赐予细川忠兴，将肥后的一半和筑后的一半赐予加藤清正。在给清正的信末尾，他若无其事地加了一句："倘若无异心、诚心归顺的话"。

正则面前当然也吊着诱饵。他许诺将尾张国内所有无主的领地都赐给清洲城主。虽不知无主之地有多少，但想来不会低于十万石。至于佐和山该给谁，他一时想不出来。

这份乐趣还是留到最后吧，家康想。

这一天，家康甚至连前田肥前的母亲芳春院也献了殷勤。收信人写的是随同来到江户的重臣村井丰后。家康盛赞了前田攻陷大圣寺城的功绩，并约定北陆之地将根据攻取情况赐予利长。接着又写道，此战结束后，便打算立即释放芳春院，并用这样一句杀手锏般的话语结尾：

"我已许久不曾亲自提笔写信。但此次实在太过满意，故而亲自执笔。"

家康感觉自己写的贼好。

<p style="margin-bottom:3em;"></p>

这期间，清洲的两位军监几乎每天都有快信飞来，催促他早日出兵，但家康对这些哀鸣充耳不闻。他现在绝不能离开江户城。

北方有毫发无损的上杉军。如果现在西进，上杉景胜那家伙一定会杀向江户城，换作自己是上杉也会这么做。当然，能想到的手段他都用了。比如命令留在宇都宫的原驯鹰师与直江兼续接触，正信似乎甚至提出愿将自己的末子作为人质送去，但似乎未能让兼续满意。

从正信的报告中，家康得到的感觉是：自己急于西进的意图被对方看透，然后被巧妙地搪塞了过去。

佐竹的动向也依然不明朗。尽管家康再三催促，义宣只答复说，如果是东政义队的三百人，倒是可以让其参加秀忠率领的中山道军，但家康婉言谢绝了这个提议。政义是在家康从小山撤退时，曾强烈主张追击的反德川巨头。这简直是恶劣的玩笑。

不只是北方的威胁。对于集结在清洲的客将们，家康也丝毫不敢掉以轻心。如果说北方是诡异，那么西方大约可以说是难以捉摸。

<p style="margin-bottom:3em;"></p>

其实，就在上月二十九日，也发生了一件能让人窥见家康疑心之重的事件。这一天，家康把已经行进到厚木（相模国爱甲郡）的黑田长政召回了小山。

面对急忙赶回的长政，家康倾诉了自己的疑虑。那就是，正则真的可以信任吗？

长政对他的疑心重感到无奈，说道：

"太夫的事您完全不必担心。他若怀有二心，我会严厉谏阻；若他不听，我便与他拼个同归于尽。总之，太夫的事就请交给我吧。"

据说家康赐予了他在长久手之战中使用过的齿朶盔和配好鞍的骏马，以激励他的斗志。这似乎是一则体现家康安心的轶事，但事情并非如此简单。实际上，家康召回长政，是为了试探他。出这个主意的是正信。

面对家康说"甲斐守和太夫过于亲近。若太夫怀有二心，甲斐守岂不也很危险？"的疑问，正信建议道：

"既然您如此怀疑，何不先将甲斐守召回试试？如果太夫真有异心，他一定会拉甲斐守一起走。"

别说正则了，家康连长政都不信任。

"那些家伙能信得过吗？"是家康的真实想法。轻易倒向这边的人，也会轻易倒向那边。贸然前往那群家伙聚集的清洲是很危险的。一不小心，说不定连脑袋都会被割走。

"喂，你说是不是？"家康逮住恰好从宇都宫回来商议的正信，开始倾诉自己的不满。

"那些家伙根本没有认识到这是他们自己的战斗。他们只是觉得，因为受到内府的恳请，看在情分上帮德川一把罢了。率领这样的乌合之众，怎么可能打得赢治部少辅？"

"的确如此。"

"缺乏统帅的士兵不过是乌合之众。一旦战况不利，他们肯定会争先恐后地逃跑。"

"正是如此。"

"我已经厌倦了讨好那些家伙。他们想投靠大坂的话，尽管去好了。"

"那么，您打算怎么做？"

"派使者去，谴责他们的怠慢。"

"您指的是什么怠慢？"

"为何不攻打眼前的岐阜城？若能攻下岐阜城给我看看，我也未尝不可相信他们的信义。"

细想起来，这是相当任性的话。但不得不承认，其中确实包含着某种可称为胜利关键的东西。这种冷酷是家康所有、而三成所没有的。

派去谴责的使者也不错。不，这更是探听客将们真实想法的好机会。如果因为被斥责就投敌，那这样的家伙根本不值得信赖。与其决战时被背叛，不如现在就把阵营划分清楚，要好得多。

正信脸上浮现出"这步棋走的真高啊"的感叹之色。^[原文“一本とられたな”，是围棋术语，意思为“被对方吃掉一子”]

"那么，派谁去当使者呢？"

"你觉得谁合适？"家康说。"最好派个愚直的人去。"

这步也很高明啊。正信由衷的佩服。确实，这差事不适合聪明人。聪明的家伙去了，会在无意中试图安抚客将们的怒气，使者必须是个能将家康的猜疑与冷酷，不加任何修饰，直截了当抛出去的人。

"村越茂助如何？"

"我认为合适。"

主仆二人对视一眼，不禁偷偷笑了。正信心里觉得，我家主子真厉害，简直想绕到家康身后去给他捏捏肩膀。

<p style="margin-bottom:3em;"></p>

村越茂助是在近江和武藏两地领有千石俸禄的旗本，今年大约三十九岁。茂助没什么特别的才能。只是，凡是被命令的事，他都会彻底执行。这个人的性格和他的长相一样，都极为刚毅。

八月十三日夜，村越茂助从江户出发。

同僚们对茂助担此大任愤愤不平，城中盛传这是"草率的使者"，意思是人选轻率。

茂助悠然自得地沿东海道西上。在滨松，他甚至顺路进城探望了堀尾吉晴。吉晴在七月十九日返回越前府中的途中，顺道拜访三河池鲤鲋的水野忠重邸时，突遭横祸，被三成的刺客加贺野井秀望砍伤，此时正在居城养病。探望吉晴，当然是家康的命令。

<p style="margin-bottom:2em;"></p>

八月十九日，茂助终于进入了清洲城。就在福岛正则怒吼"要把我们当劫材使吗"的第二天。

终于抵达的使者，被直政和忠胜像绑架一样强行拉进一间屋子。

"来，把主公的口谕说给我们听听。"

茂助似乎犹豫了一下，但对方毕竟是主公的代表，不能隐瞒。茂助复述了家康亲口教给他的原话。

两位军监脸色铁青。

"茂助，茂助，忘了刚才的口谕吧。"直政说。"要是毫不掩饰地把那番话讲出来，那些家伙会杀了我们的。"

"情况已经那么糟了吗？"

"啊，糟透了。"

军监们一起围上来晓以利害，给他灌输了新的说辞。

"你要这么说：'我身染风寒，以致迟迟未能出阵。但近日即将亲自出马，一举歼灭敌军。特派村越茂助前来告知此意。' 来，说一遍。"

"……"

"说！"直政板起面孔。"如果主公因为你篡改口谕而责罚你，我就代你切腹！"

茂助终于同意篡改。实在是迫不得已，毕竟对方是连主公都要敬让三分的德川家栋梁。同是家臣，与只领千石的茂助相比，简直是云泥之别。

被灌输了新口谕的使者被带到大广间，在客将们面前坐下。

"来，请讲。"

直政捏着嗓子，用甜得像哄小猫一样的声音说道。

"各位大人，连日驻留，诸位辛苦了。"

茂助的开场白因紧张而微微颤抖。两位军监大大地点了点头，仿佛在说：就这样，很好。

"在下现在传达口谕。"

说到这里，茂助忽然清了清嗓子。

直政感到一丝不祥的预感，他想起了人们对茂助的评价——一旦咬住，只要家康不说松口就绝不松口。

不幸的是，预感成真了。茂助对家康教给他的口谕，一字一句都未加修改。

"口谕如下：'诸位驻留军中，辛劳可知。望诸位速速拿出敌我之分的明确证据来。倘若有所闪失，以致延误军机，则日后决战堪忧。拿出证据以后，我将立即出马，讨伐敌军。' 以上。"

所幸，茂助说完话后并未被客将们勒死。在场最容易被暴躁的客将们攻击的当属直政，此刻直政只是露出像做错事的少年般模糊的笑容。

客将们阴沉地沉默着。黑田长政轻轻叹了口气。完了，自己本该到手的几十万石这下泡汤了——

内府是发疯了吧？如水的儿子只能这么想。若是神志正常，怎么可能说出什么“不知是敌是友”“就算战死也会为你们收尸”之类的蠢话？后世的史学家，或许会将德川夺取政权失败的原因，归结到村越茂助的这次口谕上吧。

<p style="margin-bottom:3em;"></p>

忽然，一名武将猛地站了起来。是福岛正则。

清洲城主的右手握着一把白扇。茂助下意识地用双手护住了头，以为要挨打了。不只是茂助，在场所有人都这么想。

但正则接下来的举动，完全出乎所有客将的意料。

正则走到茂助面前坐下，展开白扇，"啪嗒啪嗒"地给茂助扇起风来。

"您的斥责完全正确。眼睁睁看着敌城就在眼前却按兵不动，的确是我方的过错。我们会立刻动手，定将好消息向您汇报。"

正则慰问着汗流浃背的茂助。

"您应该是姓村越吧？如此艰巨的使命，您完成得很出色。哎，岐阜城嘛，明天就攻下来给您看看。您也逗留个两三天，观观战如何？"

正则对这种话术抵抗力很弱。只要能把他的情绪调动起来，让他干什么都行，清洲城主就是这样的人。

大广间顿时轰然骚动起来。

托此之福，茂助完成任务后，竟成了一万石的大名。

