# 第七十章 东部战线 {-} 

西边的西军每战必败，但东边则另当别论。

在东国的东西对决中，西军正呈现出压倒性的优势。受家康委派协助征讨上杉、被任命为会津侵攻的主力大将的堀、伊达、最上诸大名之中，最先响应的似乎是越后的堀秀治。

离开小山之际，家康命令立即停止战斗行为，并反复保证即使自己离开，也会将秀忠留在宇都宫，无需任何担心。然而，对于告发上杉氏备战、成为大乱导火索之一的堀监物直政来说，这份苦心写就的书信，并非什么了不得的安慰。

<p style="margin-bottom:3em;"></p>

堀家执政·监物的噩梦，始于七月二十五日柏崎爆发的一揆。据说由上杉氏正规军指挥的一揆军多达八千余人。

八千人，这是足以匹敌堀家动员能力的大军。从那天起，堀、村上、沟口等越后的大名晚上全都睡不着觉了。不过，从他们在家康的告密信中诉苦"担心一揆何时爆发，无法高枕安眠"来判断，监物的失眠或许已经转为慢性，成为失眠症了。

总之，监物几乎每天都会派快马前往佐和山，恳求宽恕。

"如果上方能赐予某一国，将越后奉还给景胜卿也无不可。"

监物甚至写下了如此决绝的话语。

这也不一定是权宜之计，因为堀氏出身于伊势。监物也想过：既然上杉想要，就把越后给上杉打回去算了。

三成很快回信，表示嘉纳堀家的请求。信中写道：已将贵家意向传达给会津，中纳言似乎也很欣喜。

监物期待一揆能早日平息。但无可奈何的是，一揆丝毫没有减弱的迹象。监物指责上杉违反协定。

不久，三成的书信抵达。

"上杉方也在竭力说服一揆军，但对方毕竟是土寇。希望你能理解，上杉的影响力也有其限度，完全镇压恐怕还需要一些时间。"

如果需要时间的结果，是不幸地导致我方战死，那该如何是好？那位以机敏著称的奉行，却疏忽大意地完全没有提及此事。

八月八日，越后为之震撼。因为当天有流言称，景胜本人将率领本庄繁长、甘糟景继、津川弹正等三万余人，从津川口来袭。结果就是，监物的失眠症一直持续到西部战线捷报传来的九月二十一日。

<p style="margin-bottom:3em;"></p>

伊达政宗的处境也相当具有喜剧性。

堀监物只是告密，而他却实际攻下了上杉家的白石城。话说回来，政宗得知东军从小山掉头西上的消息，是在八月三日。告知他此事的是井伊直政。这个消息，从根本上颠覆了他想要充分利用德川的力量，恢复旧领会津的意图。

政宗立刻提笔。

"应当火速攻入会津。若延期，不知会生出何等祸事。只要讨伐了上杉，治部少辅之流不就能随意处置了吗？"

简直就像恫吓。家康似乎颇为头疼。

家康并未因白石城陷落而欣喜。既然已决定西征优先，任何挑衅上杉的行为，不管是什么，都只能是凶兆。若东西两面同时开战，等待德川的命运只有灭亡。

但也不能劈头盖脸地斥责。首先，政宗没有任何可供斥责的把柄。家康于七月二十一日要求东国诸将攻入会津。政宗忠实地遵守了这一点。讽刺的是，只有政宗遵守了家康的命令。

家康通过迄今的交往，痛切地了解到对方一旦闹起别扭，会变成多么可怕的敌人。政宗是个自尊心极强的男人，为了利益可以面不改色地说谎、干出不义之事，唯独自尊心高得令人厌烦。如果惹怒了伊达，那家伙说不定会为了让人明白惹他的代价有多高昂，而匍匐在上杉面前，志愿担任攻击江户城的先锋。

但是，在不触怒他的情况下，让他从白石城撤退也并非没有办法，那就是约定给予恩赏。关于加增的幅度，家康早有腹案：五十万石。这大致相当于那个因煽动一揆而被太阁三次削藩的北方枭雄旧领的一半。

家康派遣中泽主悦介作为特使前往白石。事情顺利得毫无周折。政宗于八月十四日，只留下老将石川昭光在白石城，便匆匆撤回北目城。

八月二十二日，家康重新写下了知行宛行状。这一天他约定的新领是刈田、伊达、信夫、二本松、塩松、田村、长井共计七郡，加增额为四十九万五千八百石。这份宛行状，加上伊达原有的旧领将超过百万石，因此此后被称为"百万石保证书"。这份保证书于八月底，由堺的茶人今井宗薰送达北目城。

读完后，政宗薄薄的嘴唇上，浮现出若有若无的笑意。仅此而已。

这是家康从未见过的，此人另一副面孔。

<p style="margin-bottom:3em;"></p>

同一天，政宗向福岛城将·本庄繁长派遣了内应的使者。

不过，此时政宗让使者传达的言辞，并未记录在上杉家的家谱，也未见于伊达家的记录。政宗日后还不至于好心到留下对自己不利的证据。

但是，兼续回复繁长的书信中，有这样一句话：

>"关东御出马之际，政宗是否会同阵？"

政宗或许说了类似于"进攻江户时请带上我"这样的话。书信的日期是九月三日。

一切都要看形势发展。如果家康在对三成之战中获胜，那就没有任何问题。那时政宗打算吞下约定的五十万石，然后像一只蛤蟆似的，蹲在那里、若无其事地不动声色。

但如果德川败了……

想到那一步，政宗露出了令人不快的笑容。那时，这个胆大妄为的家伙想道：我就会成为上杉的先锋，去攻击江户吧。

数日后，繁长的使者来到北目城。口信非常简短。

"上杉理解了伊达的意图。"

仅此而已。

使者完全没有提及政宗所担心的白石城归还问题。一副佯装不知的绝妙姿态，仿佛在说：好不容易攻下来的，白石城暂且由伊达家保管吧。

政宗不禁对邻国的大守感到一丝畏惧。景胜没有拘泥于小恩怨。他似乎着眼于更宏大的事物。

<p style="margin-bottom:3em;"></p>

"我被内府抛弃了。"

最上义光颓然就地坐下。

此刻，义光手中拿着家康七月二十九日的信。内容是：西征优先，特此告知。

义光由衷后悔自己被推举为米泽口的主将。按理说如果其他大名接受了主将的荣誉，自己肯定会勃然大怒，但如今这念头丝毫未浮现于脑海。尤其让他头疼的是，自己让配属在米泽口的南部、秋田、六乡、仁贺保等诸将进驻了山形城。义光心想，那真是失策。若没有那一步，自己本可以装作若无其事，声称最上压根没有进攻上杉的意图。

可另一方面，当驻防领内的诸将因三成举兵的消息而惊惶、开始归国时，他又怒火中烧。

理由是："未经总大将许可！"

义光屏息凝神，侧耳倾听来自会津的动静。

八月初，景胜派遣水原亲宪、前田利太二人至米泽口。据说各城将的调动，在福岛以南也频繁进行。

上杉企图吞并最上，这几乎可以肯定。上杉领地被最上领地分割为二。上杉中纳言及其执政想要连接两片领地，为防备预想中德川军的再次来袭，这丝毫不足为奇。

八月十八日，最上义光终于按捺不住，提笔写信。收信人是直江兼续。

<p style="margin-bottom:2em;"></p>

>一、听闻此次贵方有意发兵进攻本最上领地，特致此书。今后，我将如同上杉家臣一样，为景胜卿奉公。
>
>一、往年景胜卿下向若松之时，我曾远赴山科、大屋、毛原，如同侍奉主君般相送。
>
>一、彼时，我曾派遣快马回国，命嫡子义康在景胜卿抵达若松的次日便出仕，如同拜谒主君般致意。

>一、家康在大坂城召开讨伐上杉的军议时，连日通过留守居役千坂对马守，将军议内容通报给会津。
>
>一、为何要攻击最上？对于在上杉领地有冒犯之举的政宗不闻不问，却连一个足轻都不曾放入上杉领地的最上反倒成了攻击目标？这令人困惑。
>
>一、若蒙俯允上述条款，愿将嫡子义康送作人质。当然，重臣的人质也请随时指示。此外，我愿率领一万军队，随时效命。以上事宜，恳请转达景胜卿。

<p style="margin-bottom:2em;"></p>

不顾廉耻，正是无条件投降。

<p style="margin-bottom:3em;"></p>

上杉成功策反的，不仅仅是堀、村上、沟口、伊达、最上，还有出羽秋田凑城主·秋田实季、横手城主·小野寺义道等人，也匆匆忙忙将特使送往会津。八月二十五日，上杉景胜向在坂的两位大老、四位奉行报告了东国形势，笔调欢欣雀跃。

"最上与伊达的问题一旦解决，将与佐竹商议后，舍弃一切攻入关东。堀秀治因向江户送出人质等，表现出与德川同伙的姿态，本打算命令旧领的领民发动一揆，并派遣少许人员，将其剿灭。然而，突闻秀治正为秀赖公勉力尽忠，大为惊讶。随即提议和睦，并中止了一揆。沟口、村上二人从一开始便是我方同伴，尤其没有问题。南部、仙北、由利的诸将，每日都有使者前来会津。皆表示愿为秀赖公奉公。因应对各路颇费时日，延误了攻入关东，心急如焚。近日内需与佐竹商议。另，关于东国处置，伊达和最上均表示，只要指示，便会立刻赶来成为我方同伴，敬请放心。"

<p style="margin-bottom:3em;"></p>

但是，经由真田领上田送出的这封书信，似乎未能送达三成之手。此时，中山道和东海道，主要街道均已在东军控制之下。信使空手而返上田。

于是，真田昌幸得以偷阅书信。这位"小信玄"的惊愕非同小可。

"连伊达、最上，乃至南部都策反了吗？这岂非意味着常陆以北的土地，全盘归了那家伙？"

老人感受到一种冲击，仿佛北方骤然出现了一个全新的帝国。

昌幸丝毫不怀疑书信内容的真实性。没人比他更清楚，会津的太守绝对不是个夸夸其谈的人。

