# 第七十六章 两股潮流 {-}

九月八日，驻屯在赤坂的东军诸将，完全没有察觉到数十万石加增的“机会”，正从仅仅数百米外悠然地经过——在决战临近、还有七天就要打响的这一天，三成竟在大白天只带了四五个随从侍卫，堂而皇之地回到了彦兵卫的城池。

大垣与赤坂之间的对峙，在三成秘密潜往佐和山期间当然仍在继续。在此期间，两军数次发生小规模冲突。令人恼火的是，每次交战都是西军败北。大垣以北四公里处的会根城被刈谷城主水野胜成夺回；西保、本乡两城被烧毁；池尻城、长松城也被松平康长占据，情形狼狈。

<p style="margin-bottom:3em"></p>

不过，也并非没有可喜之事。九月三日，大谷吉继率领胁坂、小川、朽木、赤座、户田、平塚诸队抵达山中村，堵住了从关原通往近江的中山道。只要盟友吉继不被攻破，佐和山就安泰，三成觉得，这下稳了。

四日，驻守濑田的熊谷直盛、垣见一直、相良赖房、秋月种长、高桥元种等九州诸将，经由佐和山抵达大垣，在城西的河侧扎营。他们都是决战当天将被编入大垣城守备队的武将；七日，伊势方面军两万八千人进入关原，在南宫山布阵。成员包括毛利秀元、吉川广家、长曾我部盛亲、安国寺惠琼、长束正家等人。至此，集结于大垣、关原近郊的西军已超过五万。尚未在美浓现身的，大约只有大阪的毛利辉元队和滞留在高宫（彦根）的小早川队一万五千人。

<p style="margin-bottom:3em"></p>

据记载，十日，三成去视察了毛利秀元布阵的南宫山。无论如何，这才是西军的主力。但是，回到大垣城的这位能吏，心情却糟糕透顶。

顺便一提，南宫山是位于垂井东南、关原地区最险峻的独立丘陵。海拔虽然只有四百一十九米，但山势意外地深幽，通往山顶有大约四公里长的陡坡。

“托它的福，我欣赏到了绝佳的风景。”三成对着岛左近发牢骚。

“我中途喘不上气就折返了，从毛利和吉川布阵的山顶望下去，别说大阪，说不定连安艺都能望见。”

“他们倒是不会为煮饭喝水发愁啊？”左近说出了理所当然的疑问。

“大概是从南宫神社那里弄来的吧。算了，他们既然在炮弹飞不到的山顶布阵，喝水的辛苦就只好忍耐了。”

“在那么高的山上，毛利到底打算干什么？”

“这你去问广家可能更快些。我只知道，广家可不是为了让士兵锻炼腿脚才爬那座山的。”

“真是靠不住的盟友啊。”

“他们根本就没打算打仗。毛利可是大阪的总大将啊，不打赢就会被消灭。内府不可能放过他们。可那家伙不明白这一点。”

“不如命令他下到山麓更……”

“我？我在名义上只是大阪方的一员部将。可以请求，但没有命令的权限。”

“安国寺、长束、长曾我部的士气如何？”

“士气也不咋地，三个人都在南宫山背面半山腰附近像筑巢一样。不过我那边的阵地也有佐和山那么高。”

“这么说，从山上下来要花半个时辰呢。”

“左近，不用担心。毛利中纳言会在十二、三日之前拥戴秀赖大人出马的。已经约定好了。广家会打的。总大将一出现，作为毛利的参谋，广家也不可能悠闲地在山顶被怯懦之风吹着吧。”

<p style="margin-bottom:3em"></p>

或许是与左近的对话触发了什么，这一天，三成又派快马去大阪催促辉元出马。西军四分五裂。总大将不出现，就无法决一胜负。

第二天，第三天，三成的忧郁持续着。间谍带回的情报全都没什么好消息。其中，最让他神经受刺激的，是东军的密使半公开地出入盟友诸将阵地的报告。

据说，黑田长政和德永寿昌的使者频繁造访南宫山的广家处；而藤堂高虎和一柳直盛的使者，也数次出入驻屯在关原西南山中村的胁坂和小川的阵地。广家倾心于黑田如水是众所周知的事，胁坂安治从被称为“栗之甚内”的时代起就与高虎投缘。而且，小川祐忠的妻子是直盛的叔母。

“背叛也不是不可能的事。”三成说。“不，是很有可能的事。”

“还有别的。”大音新介压低了声音。

“你该不会要说，连宇喜多中纳言和大谷刑部那里，也有内府的密使出没吧？”

“正是如此，就是这样。”

“荒唐！新介，你究竟是从哪里听来这种谣言的？”

“是从中纳言大人和刑部大人那里直接听说的。”

“哦！”

“大概是他们觉得，与其让您从别处听到，不如……”

“瓜田李下吗？不管什么谣言，他们两个是绝不可能背叛的。究竟是谁，胆敢去策反他们？”

“据中纳言大人说，是细川大人和他的旧臣户川达安送来了使者。”

“三灾吗？”三成扭曲了面孔。

“三灾”是忠兴的外号。同伴把宫津城主的号“三斋”改了一下，这样称呼他。

“三灾到底说了什么来劝诱？”

“说什么，您的亲戚前田利长卿近日攻落了大圣寺城，在北国显示了武威。您趁现在向内府尽忠才更划算。大概就是这样的说辞。”

“确实像是三灾会说的事。那么，去刑部那边的是谁？”

“是井伊和本多。”

“那两个人吗？饵料是什么？”

“说是如果站在内府一边……”

“也就是说，如果抛弃我，对吧。”

“答应给您越前半个国，刑部大人笑着说。”

“要钓刑部那样的人物，只给越前半个国，内府还真是小气啊。换了我，大概会说把前田肥前的领地全部献上吧。”

“问题是胁坂和小川。”

“他们没来说有密使来过吧。”

“是的。”

“新介，别做出那副胃疼的表情。”

“您这么说……”

“甚内和小川都是被已故殿下提拔为大名的。他们不会忘记那份厚恩，做出投靠内府那种卑鄙的事吧。”

这是非常乐观的看法。三成彻底缺乏怀疑人的能力。沐浴了太阁恩泽的人，无需多说，就该为秀赖献出生命。三成心中有一个严格的规范：人应当如此。他无法理解，人为了自己的利益，会对大多数不正当行为睁一只眼闭一只眼。偏离规范的都是坏人。从这个意义上说，这位能吏永远是个长不大的孩子。

<p style="margin-bottom:3em"></p>

主从的对话继续着。

“但是，密使大摇大摆地进进出出，也真叫人头疼。首先这影响就不好。”

“那怎么办呢？”

“他们驻扎的赤坂在大垣和关原中间，在这里监视是不可能的。”

“照这样下去，内府的密使没来的，恐怕就只有我们石田家了。”

“别那么灰心。”三成顽皮地眨了一只眼。“说不定哪天内府的人也会混到我们家来呢。”

“这玩笑可不好笑。”

“来了就恭敬地请进来吧。我倒想听听内府到底打算给我什么许诺。哈哈哈……”

<p style="margin-bottom:3em"></p>

新介离开后，三成直到深夜都在不停地写密信，他怀着“绝不能输给内府”的心情，企图让东军诸将倒戈到自己这边。

这一天，这位能吏向宫部长熙、加藤嘉明、筒井定次、寺泽广高等看起来有说服可能的武将们，许诺了令人咋舌的赏赐。其中，对老友“田兵”田中吉政，他写道：“若肯相助秀赖公，将赐予三河、远江。”

真是大手笔的挥霍。

<p style="margin-bottom:3em"></p>

十二日，毛利辉元极其轻易地违背了约定。按照计划，他本应差不多到达佐和山了，但不仅他本人，连辉元的亲卫队士出发前往大阪的消息都没有。

辉元并无恶意。当他打算出马、开始准备时，一个传闻传入了这位好人的耳中：据说，毛利离开大阪城后，奉行增田长盛会投靠内府。

为此，辉元放下了已经抬起来的屁股。仅此而已。家康公开密信的效果，几经周折，在这样一个地方显现出了意想不到的效果。

“大阪的主力部队似乎不会来了。”

传闻当天就扩散到了大垣城内外。西军诸将的士气更加低落。据《武家事纪》记载，当时在大阪城，仅秀赖的小姓众七千五百人、马回组八千人、弓铁炮足轻五千九百人、前备后备六千七百人等亲卫部队，就有两万八千大军无所事事。加上毛利、前田玄以、增田等人的士兵，大阪城守备队达到四万二千人。

如此庞大的兵力在闲置，士气自然也低落了。

<p style="margin-bottom:3em"></p>

十二日夜，三成在大垣城内的一间屋子里，给长盛写了一封直言不讳的书信。

书信相当长，但只摘录要点的话，大致如下：

“敌人在赤坂集结，却毫无动静，似乎在等待着什么，大家都觉得很奇怪。”

“前天，我去拜访了长束和安国寺的营地，从未如此吃惊。因为他们的营地在高高的山上，人马的饮水都没有，那样的话，万一有事，连兵力调动都无法做到。他们似乎格外谨慎，只顾自身安全。既然我方都感到可疑，敌人想必觉得很好笑。总之，我真想让你哪怕看一眼这里的状况。无论是敌人那呆傻的样子，还是我方的不和，恐怕你都难以想象。”

“总之，像这样一天天拖延下去，我方军心难以揣测，很是困扰。敌我双方的底层士兵都在风传，说你与家康暗中有了默契，人质的妻子儿女一个都不会被杀。去犬山增援的那帮人背叛，据说也是因为这个缘故。如果能处死三五个敌方的人质，那帮人或许也会认真起来吧。暂时不杀的人质，可否移送到宫岛？请务必斟酌。”

“关于大津的京极高次，希望这次能彻底处分。高次的弟弟高知也在当地干了不少坏事，令人头疼。究竟这都是些什么人啊。”

“本地的战事，如果诸将能够齐心，二十天内击破敌阵也不是不可能，但照此下去，我担心我方内部会出现叛徒。岛津义弘、小西行长也同意这个看法。”

“从近江出动的小早川势，万一有什么不测，那真是太麻烦了。”

“既然家康没有西上，毛利辉元不出马也是当然的。下面的人似乎对此抱有疑虑，各种说法都有。”

“正如我多次提出的，现在正是使用金银的时候。我连自己手头的都已经全部拿出来了。我还招募了人，手头拮据的程度还望您体察。”

“宇喜多秀家的决心令人钦佩，他抱定了舍弃性命的姿态。岛津、小西也同样。”

“丹后方面的人员应该已经不需要了，希望您能调遣哪怕一部分到本地来。”

书信在这里戛然而止。

三成大概是觉得，如此诉苦一番，辉元就会改变主意，出马相助吧。总之，他又是责备，又是发牢骚，又是哀求，忙得不亦乐乎。

但是，这封信并没有送到长盛手中。因为信使在大津偶然被前去高次处办事的北面武士捕获，交到了东军手中，因此书信落到了家康手里。这等于说，我方把西军的最高机密主动告诉了对方。

<p style="margin-bottom:3em"></p>

次日，九月十三日，三成遇到了一件高兴事。事情始于他与大音新介的这样一段对话。

“主公，主公，终于来了！”

“吵什么，什么来了？”

“萨摩，岛津的将士们从午后开始，陆续到达大垣了。”

“终于来了吗。”三成坐立不安地站起来。他搓着手，几乎难以抑制。

“那么，赶来的是谁和谁？”

“首先是长寿院盛淳大人。”

“这个名字我知道。盛淳应该是吉田的地头职吧。”

“还有伊势贞成大人、大田吉兵卫大人、中马大藏大人、相良吉右卫门大人、后醍院喜兵卫大人……”

“不都是一骑当千的强者吗？真可靠啊。”

“听说中马一听到惟新大人的危急，就扔下正在干的农活，突然朝大垣跑了过来。”

“连家都没回吗？盘缠怎么解决的？”

“据说睡在寺庙或路边，吃饭靠町上人家施舍。”

“要饭来的吗？那位老人真是有好家臣啊。”

“更惊人的是，据说那些乡士只用了十三天就跑过了中国地区、畿内。”

“真是可怕的家伙们。那么，我问你，我到底该算得到了多少生力军呢？”

“这个还不清楚。因为乡士们都是两三个人，或者五六个，零零散散地赶来的。”

“零零散散啊。”三成稍微歪了歪头。“但岛津是六十万石的大大名。两次战役中，那家动员了一万二千四百兵力。即便是零零散散，恐怕也不会少于三千吧。”

“那样就太好了。”

“嗯，等着瞧吧。”三成独自亢奋起来。

“新介，有意思起来了。那位老人据说迄今上战场五十一次，五十一次都听到了凯歌。希望第五十二次也能如愿。”

然而，三成的喜悦只持续到傍晚。扛着铠甲箱赶来的乡士，最终只有七十人。

“只有七十人吗……”

三成急忙中止了去岛津营地慰问的计划。有点过于势利，这是三成的坏毛病。

<p style="margin-bottom:3em"></p>

三成在写给长盛的信中，反复叹息小早川队可疑的动向，而那个傲慢的小子，终于在九月十四日，于美浓现身了。

但是，西军士兵中没有发出欢呼声，因为那小子的动向未免太诡异了。

八月一日，攻落伏见城后，秀秋以修理兵器为由，一度返回了大阪。但是，小早川队一万五千人是仅次于宇喜多队的大军。不能让他们闲置着，秀家便命令他前往伊势。

秀秋八月十七日再次东进。但无论等多久，他也没有到达伊势。

“我平日多病，当前难以履行军役。”

这样一封冷淡的书信被送到了大阪。

结果，秀秋整个八月都停留在石部。九月初，他离开近江，终于进入伊势，但在此又在铃鹿花费了五六天狩猎游玩，然后再次返回近江的高宫。

“他到底在想什么？”三成大为神经紧张。“莫非想攻打佐和山城吗？”

高宫就在佐和山眼皮底下。这小子或许是打算等待西军败报，然后第一个攻入佐和山。不这样想，就无法解释他特意在高宫布阵的理由。

此外，谍报称秀秋在此期间曾两次向关东派出密使，这也大大刺激了诸将的神经。

<p style="margin-bottom:3em"></p>

在大垣城内举行的评定会上，关于如何处理这小子的问题沸腾了。最理想的办法是没收秀秋的大军。

“即使使用计策，也要把金吾扣为人质，幽禁在佐和山。”

秀家和吉继这样主张，户田胜成和平塚为广热烈支持。

最为激进的是岛津义弘：“等战斗开始他再乱来就没办法了。应该现在把他杀掉。”

老人用极其平静的声音说道。

最终决定：首先向高宫派去问罪使，伺机将金吾扣为人质。如果家中有人骚乱，当场将金吾刺杀——评定大致在这样的方向上达成了一致。

<p style="margin-bottom:3em"></p>

但是，西军派出的户田、平塚两名刺客，无功而返。据说金吾异常谨慎，连面都不肯露。他的意向通过平冈、稻叶两位重臣传达给了问罪使。

“本想返回京都疗养，但既然二位受命前来，近日内将前往大垣，听从您的指示。”

秀秋这样说道。这是靠不住的话，但再进一步刺激也需考虑，尤其是在京极高次已经背叛的当下。

十四日，离开高宫的秀秋将兵力推进到柏原，但一步也没有再靠近大垣。

并且，他向大垣城送来了这样一封问候信。

“因病延迟出阵期间，听说流言四起，故而前来。但被议论怀有二心的我，就此进入大垣城有所顾虑。暂且于城外布阵，待与关东军交战之后，再行拜见。”

大致是这样一个内容。

“是吗，金吾大人是不愿意进大垣城啊。”接见使者的秀家不禁苦笑，接着说道，“既然如此，就暂且让他在松尾山麓布阵好了。”

“这样也好。”三成想。

<p style="margin-bottom:3em"></p>

秀秋的提议，在某种意义上对西军也很有利。万一发生笼城的情况，在城内放一支敌友不明的可疑部队，无异于睡在发热的火药上。

同样，将其放在大垣城郊外也并非上策。如果内通属实，这小子很可能在东军接近时，趁机跑到攻城方那边去。

关键在于不能给他内通的机会。烂苹果最好隔离。作为隔离场所，松尾山最合适。那里既远离大垣也远离赤坂，而且山中村有大谷吉继在。

“刑部会妥善看住他的。”三成想。

被誉为当代第一武略的吉继，应该不会被一个小儿欺骗。

<p style="margin-bottom:3em"></p>

实际上，大谷吉继的反应非常迅速。小早川队刚登上松尾山山顶，吉继就将自己的本阵移到藤川台，并将胁坂、小川、朽木、赤座四队四千三百人部署在松尾山麓流过的藤古川沿岸要地。他要堵住小早川队通往平地的出口。

这一次阵型变换，露骨得仿佛在说敌人就是松尾山上的小早川队。吉继是想让对方明白，自己明确地把小早川队视为敌人。他试图通过传达这种巨大的厌恶感，让这小子打消背叛的念头。

结束所有防御准备后，吉继坐着板轿，去拜访了据守在山顶古垒的秀秋。

面对被两名重臣陪同、勉勉强强出来见面的秀秋，吉继说道：

“大垣的诸将中，有不少人相信金吾大人与关东内通，主张杀了你。但是，没有确凿证据就谋杀的话，疼爱您、让您继承小早川家的太阁殿下的灵魂也会震怒吧。请好好考虑这一点，不要弄错了进退。”

秀秋微微动了一下，吉继没有看到。虽然吉继从浅葱色的绢袋中露出了眼睛，但最近这眼睛几乎也不起作用了，只是偶尔有白色的东西一闪一闪地明灭。

但是凭借别的知觉，吉继依然感觉到对方似乎动了一下，

“我代主人回答。”有人插嘴道。

“是稻叶正成大人吧。听声音我记得。”

“产生流言，完全是因为生病导致出阵延迟。”

“嗯。”

“主人自幼深受太阁殿下大恩，没有一天不提及此事。”

“嗯。”

“这样的主人，怎么会对不谙世事的幼君怀有背叛之心呢？”

吉继缓缓地站了起来。正成的辩解即使是谎言，也未免编的太假了。他站起来的样子，仿佛在说自己再也无法忍耐一瞬。还好，不用担心被读到脸色。这位身患顽疾的武将，这一天第一次想感谢自己从头到脚蒙着袋子。

<p style="margin-bottom:3em"></p>

同日，秀家和三成向伊势派出快使，召请正在围攻福岛正赖的长岛城的锅岛胜茂。但是，胜茂最终没有动。他说有被追击之虞，要求派遣交替部队。

十三日离开清洲的家康一行，在太阳还高的时候进入了岐阜城下，百百纲家的宅邸被安排作为宿馆，先到的客将们称自己来迎接，纷纷前来问候。不知不觉间，这一天就过去了。

次日十四日黎明前，一行人草草吃过早饭，离开了岐阜。这一天，家康也表现得精明得让人生厌。他让本队走中山道，自己只带了五百精兵，沿旧道前进。

家康从心底里害怕毛利辉元拥戴秀赖出现在战场上，他现在只担心这一点。如果秀赖和辉元出马，战斗就会输。吉川广家也好，小早川秀秋也好，迄今为止的暗中活动都会抹嘴不认，装出若无其事的样子，转而要取自己的首级。到那时福岛正则会有何反应，只有天知道。

但是，只要没有自己到达赤坂的谍报传到，辉元就会继续在金城铁壁的大阪城中打盹吧。家康由衷地希望如此。

<p style="margin-bottom:3em"></p>

悄悄离开岐阜城下的一行人，首先朝着木田渡口前进。

“虽然会绕一点路，但为了小心起见，请务必经由木田。”

提出这个建议的是稻叶贞通。贞通是原会根城主，对这一带的地理，几乎找不到比他更熟悉的人。

犬山降将贞通的献身精神令人感动得落泪。当家康渡过长良川的架桥——那只是连接起数十艘鹈鹕船的简陋之物——时，贞通殷勤地捧起家康的手，甚至弯着腰为他引路。

“郡上侍从，不冷吗？”

家康对只穿一件墨衣、被河风吹着的贞通表示慰劳，他也值得慰劳。

贞通是分散在美浓、伊势的一族之长。他的影响力巨大，随着犬山开城，所有姓稻叶的大名和小领主，全都转到了这边。

并且，家康在这一族中还有另一个无论如何都期待其好意的人。

<p style="margin-bottom:3em"></p>

“小早川家的重臣稻叶正成，应该是你的……”

家康若无其事地提到了那个名字。

“是我下面弟弟重通的女婿。”

“他是个怎样的人物？”

贞通犹豫了。要简洁地形容这个义外甥颇为困难。正成是个美男子。但性格阴沉、虚无，在金钱和女人方面不检点。

“一言以蔽之，”经过一番苦战，贞通终于找到了适合这个麻烦外甥的形容，“是个相当厉害的角色。”

贞通的评价果然正确。他外甥的继室，也是同族的女儿，后来成了三代将军的乳母，正成的外孙中，后来出了两位大老。

“是厉害角色吗。”家康重复道。“你们关系亲近吗？”

“您是指……”

“有没有书信往来？”

“那是常有的事。”

“那么，这次贵一族协助我方的经过，也……”

措辞有些微妙，但幸好贞通没有误解对方的真意。

“当然，为了能奉公如意，我已反复叮嘱过。”

<p style="margin-bottom:3em"></p>

“话虽如此，我这个人也真奇怪啊。”再次在轿中摇晃时，家康这样想。

金吾送来了两次内通的使者。但他连见都没见。总之，让人心里发毛。那是一种仿佛触摸了某种说不清道不明的软体动物般的不快和恐惧。对于那种靠不住的愚者，骂声远比温柔的话语更合适。

与其借助那家伙的力量，不如输了更好。要是在决战中途他变了心，自己五十九年的修炼瞬间就会化为泥泞。家康就是这样想的。

但是，这一天，直觉执拗地反驳着他的自尊心。在迫在眉睫的决战中，他总感觉小早川会扮演某种决定性的角色。麻烦的是，这种想法越是接近决战地，就越是难以摆脱。

“果然，这里还是应该摒弃骄傲……”

家康继续摇晃着。内心的振幅远比轿子的摇晃大得多。

<p style="margin-bottom:3em"></p>

正午，家康终于抵达赤坂，进入了预先在山顶准备好的本营。本营姑且算是两层建筑。虽然要爬绳梯让人吃不消，但二楼好歹是榻榻米房间。

朝东开的窗户对面，意想不到地能清楚望见大垣城。或许是因为板壁挡住了三个方向的视野，从那扇窗只能看到大垣城。

“治部少辅现在就在那里。”

家康屏息凝神地望着彦兵卫的城池。神情严肃。

家康刚一离开窗边，客将们便仿佛等待已久似的，前来问候和报告。真正带来值得倾听的消息的，只有黑田长政。长政不知用了什么手段，似乎已大体成功让金吾秀秋内应。

“那么，这不是已经赢了吗？”家康发出了兴奋的声音。

详细的经过也不想听了。总之，这样一来不用弄脏自己的手了。这是最令人感激的。

<p style="margin-bottom:3em"></p>

赶走客将们之后，家康坐到窗边，读起了那封三成的书信——它意外地由增田长盛变成了自己这个收信人。

送信来的是京极家的家臣。从北面武士手中得到书信的高次，据说因其内容大惊失色，立刻决定派出快马。

怪不得会大惊失色。

家康好几次吃吃地笑。

其中，读到“哀哉，哀哉，真想让你看一眼我这里的状况”这一段时，他不禁喷笑了出来。

“让我看了好东西。”家康开玩笑说。“幸好是我收到了。如果长盛收到这么一封哀伤的书信，说不定会想从大阪逃走吧。”

这书信富含宝贵的暗示：吉川广家毫无战意，以及毛利辉元似乎打消了出马的念头，这些对家康都极有参考价值。

既然知道大阪方的总大将不会来，那么隐藏自己到达的消息就毫无意义了。

“立起马标和大旗。”

家康对持筒物头渡边半藏说道。

半藏面无表情地将金扇马标朝着大垣城竖起。表示家康所在位置的葵纹大旗七面、源氏白旗二十面，迎着此时的风，在深秋的天空中缓缓飘动。