# 第八十一章 绪战 {-}

那时，三成也同样在笹尾山山腰处心神不宁地踱来踱去。纵使他凝神细看，也不可能看见数千军马朝这边疾驰而来的景象，但从那震得地面轰响、逐渐逼近的马蹄声中，他已明白那是怎么回事了。

突然，从右手边的南天满山的山麓一带，数千挺铁炮喷吐火焰的声响冲天而起。刺耳的嘶鸣与惨叫声同时爆发。平原方向也传来与之呼应的射击声。大概有七八百挺吧——三成在心里估计对方的数目。

枪战中，宇喜多队占据着压倒性的优势。山麓处响起的枪声更多，间隔也短得多。虽然枪声似乎只传到桃配山一次，但它一直在反复响起。这时，北天满山附近又响起了新的枪声。小西队、岛津队似乎也进入了交战状态。

<p style="margin-bottom:3em;"></p>

三成焦躁不安地在草地上来回走着。就在这时，朝阳穿过厚厚的浓雾照射下来，雾气以惊人的速度开始移动。

三成被眼前巨大的景象压倒了。眼前的景象完全无视了近大远小的法则。因为雾气和逆光，山峦的排列一塌糊涂。离笹尾山最近的天满山那两座隆起，不知怎的，看上去几乎与正面的松尾山并排而立。左手边也发生了同样的错乱。比起丸山，更远处的南宫山颜色浓淡要鲜明得多。

但这只是一瞬间的事。风势更大了，此前一直如同屹立在汪洋大海中的岛屿般，山脚被雾气冲刷着的森林和山丘，纷纷开始抬起它们的头。大地就在他眼前伸缩、隆起。

此时，三成听到刚诞生不久的大地上，有什么沉重得毫无道理的东西，轰隆隆地朝这边滚过来的声音，那声音，正与方才在右手边平原上响起的是同一种。三成再次凝神望去。这次绝不可能看错。东军的右翼部队正从三个方向朝着一点汇聚，将原野涂抹成一片漆黑，朝这边汹涌杀来。

三成猛地一个踉跄，勉强靠杂木撑住了身体。这时攫住他的，是纯粹的恐惧。

<p style="margin-bottom:3em;"></p>

每次被拉上战场，三成总是这副模样。无论过多久，三成都无法习惯那些滚落的头颅和溢出的内脏。每逢撞见那样的光景，胃里就一阵翻涌，直想呕吐。总之，他怕死。

“我大概是个无可救药的胆小鬼。”

三成带着无奈，接受了这个难以容忍的事实。

不仅勇气，连武将所必须的那种灵光一闪，这个人物也同样欠缺。在对北条之战中，受命攻打忍城的三成采用了水攻之策。在那里，他模仿秀吉模仿得非常到家，像个拘泥于先例的官僚。结果堤防决口，己方溺死者多达二百七十余人。他事后懊悔“只要堤防不决口就好了”，也无济于事。那天，三成明白了，所谓名将，似乎不过是幸运儿的另一种说法。

不过，自那以后已过去了相当漫长的岁月。三成小心翼翼地将恐惧埋入灰烬之中，几乎成功地将其忘却了。但是，看见军马杀向笹尾山的那一瞬间，恐惧便以惊人的速度回到了他身边。

与敌人的距离已不足百米。三成闭上了眼。

这时，从岛队布阵的方向传来了铁炮齐射的声音。三成听到“咚、咚——”的响声，那声音带着令人舒畅的节奏，持续不断地响着。

三成忘我地冲下山丘。总不能转身逃跑。不管怎么说，这是属于他的战争。

<p style="margin-bottom:3em;"></p>

石田队的前卫——岛、蒲生两队所布阵的小关村前方的平坦地带，已被蜂拥的东军士兵与军马所淹没。光是率先杀到的黑田、竹中重门、细川这三队，人数恐怕就超过一万。就在三成眼前，东军还在每时每刻地增厚其阵层。稍晚于这三队，田中队、金森队，还有加藤队也纷纷杀到。

他们与石田队之间，有的仅仅是平缓的斜坡、几块水田，以及数条田埂小路而已。岛队也好、蒲生队也好，就算被一口吞掉也不足为奇。不如说，没被一口吞掉才叫奇怪。

然而，争先恐后涌来的这支混成部队，却连这区区百米左右的空间都无法轻易填满。他们此刻正被炽热的铁炮弹丸狠狠地教训着，为自己贪功冒进、毫无统一指挥、目中无人地蜂拥而上的愚蠢付出代价。

长政和忠兴既无法前进，也无法后退。岛、蒲生两队的铁炮朝着如同被黏胶缠住般挣扎的黑田队前锋，反复喷吐着火焰。一次射击便让数十名骑马武士滚落马下。既有像温柔地抱住马颈一般向前扑倒的武士，也有猛然向后翻倒的。

失去主人的马匹发狂乱奔，将己方人马踩于蹄下。这更加剧了混乱。

下一瞬间，防马栅栏唰地打开，岛队朝着好不容易爬上斜坡的敌人猛冲过去。每个士兵手中都握着足有五米的长枪。

“啊、啊！”

凄厉的悲鸣再次在四面八方响起。黑田队的逃路只剩左右两侧的水田。负伤的将兵们在泥田之中，跳起了最后的舞蹈。

仿佛忍无可忍一般，长政将骑兵队投入了突击。岛队迅速撤回栅栏之内，取而代之铁炮队又顶上前去。蓄势待发的数百挺铁炮再度喷火。胜利简单得令人扫兴，如此轻易的取胜，让三成大为震惊。

<p style="margin-bottom:3em;"></p>

三成奔回本营，望向右手边。那边，友军也明显占据着优势。

南天满山看上去一片青蓝。深蓝底色上染出“儿”字的宇喜多家旗帜与幔幕覆盖了整座山，在风中哗啦啦地翻卷着。年轻的大老将全军一万七千人分为五段，将本阵设在天满神社深处的小丘上。秀家这天，打算取下两颗首级——只要能取下这两颗首级就好，其他都无所谓。一颗是身为太阁堂兄弟却背弃丰家的那个傻瓜的首级，另一颗，则是背叛自己、投奔家康的那个重臣的首级。青年知道，户川达安正率领一队人马，就在这战场的某处。

秀家一刻不停地四处走动着，时而忧心忡忡地注视着平原。

前卫八千人的指挥官是明石扫部全登。

全登是在达安等斗将们离开宇喜多家之后，秀家提拔到执政位置上的部将。秀家将熊野保木的三万三千石俸禄给了这位以热心天主教徒而闻名的中年部将。作为执政官，全登极为能干。这位保木城守将仅用一年多时间，就重整了因主公挥霍而导致的财政危机。但他作为一军指挥官是否称职，还是个未知数。全登生性畏缩多虑，而且那下腹突出的体态，也实在称不上威风。

让那个男人担当前卫的大任，或许是勉强了——秀家心想。

雾气飘散。青年怀疑起了自己的眼睛。那个其貌不扬的中年男子，竟像老鹰戏弄麻雀一般，将蜂拥而来的福岛队六千人玩弄于股掌之上。

<p style="margin-bottom:3em;"></p>

全登的战术基本与岛左近相同。竭尽全力将敌人引到防马栅栏跟前，然后射击、突刺、追击。明石队眨眼间便将福岛队的先锋击退了四五百米。

坐镇第二阵的正则脸色铁青。

“给我打回去，打回去！”正则嘶声大喊。“先锋这副德性成何体统！愧对福岛之名！”

然而，福岛队的将士们根本没有余裕去惭愧什么武名。全登的追击就是如此迅猛。仅仅一次交锋，正则便损失了三十名有名的武士。

明石队追击着溃逃的福岛队，越过中山道，甚至涌入了平原的中央地带。饰有银制芭蕉叶的福岛大马标，精美得令人屏息，但此刻，它却被一面极为朴素不起眼、仿佛随意在黑色底布上涂了个白团子似的旗帜，毫不留情地追赶得团团转。

芭蕉叶如同被激流翻弄的树叶一般滴溜溜地打转。

倘若此时，加藤、筒井两队没有从侧面突入正得意忘形的明石队侧腹，这位清洲城主或许就将作为东军大名中第一个献上首级之人而名垂青史了。

<p style="margin-bottom:3em;"></p>

笹尾山上的三成，对于天满山彼方、晨霭中依稀朦胧的藤川台的战况，则丝毫也不担心。一个见到滚落的首级就想吐的自己，若去担心那位曾让太阁都为之惊叹的军事天才，未免也太僭越了。

大谷吉继当时正展现着完全无愧于“当世第一军略家”之名的作战手腕。

大谷队主动采取攻势，在明神一带枪声响起的同时，便越过藤古川，向正面的藤堂队二千五百、京极高知队三千、寺泽广高队二千四百发起了猛攻。吉继手下，即使将大谷本队、次子木下赖继队，以及两位与力大名户田、平冢的兵力合在一起，也不过区区二千九百人。他正是打算以先发制人的攻击来弥补兵力的不足。吉继深知初战的胜利有多么重要。一旦被狠狠揍过一次，敌人便很难轻易摆脱那种丧家犬的心态。

大谷队转瞬之间便将东军三队赶到了中山道的对面。那架势仿佛在说：回去练练再来吧。

“换个战场吧。”

寺泽广高瞬间如此想到。大谷队的将士们，个个眼中都带着仿佛被什么附了体的神色。这让这位肥前唐津八万石的大名极为不喜。

那是一群死士。和那种家伙作战，到头来只会徒然堆积尸骨罢了。

<p style="margin-bottom:3em;"></p>

“就没有个更合适点的对手吗？”

广高踩着马镫直起身子，环视平原。那是一副精明的表情，活像个放债人在拼命寻找抵押品的瑕疵。

不久，唐津城主便在北天满山山麓发现了理想的对象。东军各处的战况都不甚妙，但唯有那里，一支己方混成部队稍稍占着优势。

己方的旗帜乱七八糟。不仅有大名如古田重胜、织田有乐，连猪子一时、佐久间安政、船越景直，乃至户川达安这些俸禄不足万石的小将们，似乎也都在那里作战。

就是那个了——广高心想。他知道，“那个”正是旧友小西行长。

<p style="margin-bottom:3em;"></p>

在文禄、庆长两次战役中，广高自始至终都与行长共同行动。除了三成，大概再没有哪个大名像他那样热心地协助那位原堺商人的欺敌工作了。回国后，与加藤清正等七将发生争执时，广高也与行长一起，站在了告发武功派的一方。为了这位朋友，他曾是抱着这份心意的。

但，唐津城主并没有一直背负着这种黏黏糊糊的旧情。总而言之，行长是个好猎物。仅此而已，十分干脆。

广高匆忙召集物头们，宣布了攻击目标的变更。寺泽队二千四百人大幅向右迂回。

不久，北天满山麓又涌起了新的呐喊与马蹄声。加入了生力军寺泽队的东军，开始步步紧逼小西队。

小西队的动向，与其右邻的宇喜多队形成了极其鲜明的对照，刻印在地表之上。“儿”字旗奋力向前伸展，而小西的日章旗则节节后退。从笹尾山望去，两支队伍正以惊人的速度交错而过。

“摄津守危险了！”

然而，小西队的左侧是毫发无伤的岛津队，右侧则是宇喜多队。如果东军部队贸然深入，势必将遭到左右夹击。

<p style="margin-bottom:3em;"></p>

事态正如三成所预料的那样展开。节节后退至池寺池一带的小西队，看样子总算是在那里稳住了阵脚。

“升起狼烟！”

三成尖声叫道。

现在正是时候——三成心想。除了小西队以外，西军几乎在全线击溃、驱逐着敌人。此时，倘若南宫山上那三万余友军冲下山来，封住袋口，要取下家康的首级简直易如反掌。

三成将炽热的目光投向了敌方主将据称布阵所在的桃配山一带。他实在无法理解家康竟将本营设在那种地方。那简直就像是将脖子伸到山上的毛利军面前，在说“来砍吧”一样，那里是死地。在这方圆两公里见方的盆地之中，再没有比桃配山更适合“死地”之名的地方了。

<p style="margin-bottom:3em;"></p>

浓烟从笹尾山滚滚升起，直冲晨空。几乎同时，黑烟也从南天满山升起。这说明年轻的太老也得出了与自己相同的结论。

三成估算了一下太阳的位置，似乎已近十点了。开战竟已过去了两个小时，三成心中略感惊讶。
