# 第八十二章 博物志 {-}

这两道狼烟，桃配山上自然也望见了。第一道在稍靠右手边，第二道则仿佛是炫耀一般，正好在盆地的正对面升起，绝无看漏的可能。

本营陷入了一阵小小的恐慌。能保持镇定的，大概只有牵马老人“苏里”这样的人了。家康不停地抖着腿。每抖一下，他那肥胖身躯坐着的折凳便发出嘎吱嘎吱的讨厌声响。

对于家康来说，布阵在山顶上的毛利家参谋，几乎是个完全陌生的对手。他对这位月山城主的了解极其有限：性情激烈，似乎对安国寺惠琼燃着强烈的憎恨，对黑田如水心悦诚服，是无与伦比的战术高手——

将所知全部搜罗起来，也只有这些。然而，家康对广家的内应却信之不疑，没有一丝犹豫。这一点，与对待金吾秀秋时大不相同。

广家那封表示愿归附德川殿的书信，内容前后矛盾、毫无逻辑可言。但凡嗅到一丝可疑的气息，家康定会毫不犹豫地将密信撕碎扔掉。家康之所以相信敌方参谋怀有叛心，正是因为那书信的内容太过反常。

但是，看到狼烟的那一瞬间，确信便让位给了猜疑。当时攫住家康的，是一种恨不得抓挠头发的焦躁。

背叛过一次的男人，就会背叛第二次、第三次。为了惩罚自己，他们没法不这么做——不幸的是，家康深知这一点。

“我想听听中书的意见。”家康心想。

本多忠胜这位武将，一旦临战，便会展现出一种不可思议的敏锐直觉。被这种直觉所救，已非一次两次。若是那个男人，或许能消除自己这份不安。而且，中书是将广家拉拢到己方来的当事人之一。他作为自己的代理，为广家写了誓书。如此说来，责任的一半不也该由中书来负吗？

于是，布阵于十九女池的本多忠胜，就这样被匆匆召来了本营。

<p style="margin-bottom:3em;"></p>

“本营是否该转移？”

“此话怎讲？”

“我放心不下身后。万一这时候他们起了山贼之心呢。”

“正是。”忠胜缓缓回头望向背后的南宫山。

“那可就一触即溃了。”

“别说得好像事不关己似的。”

“那么请问，主公您若是吉川，这种时候会怎么做？”

家康一时语塞。若是自己，毫无疑问，早已冲下山去了吧。

“可是，那个男人写了誓约书啊。”家康抗辩道。他此时的心境，哪怕一根稻草也想抓住。

忠胜耸了耸肩。那意思仿佛是：这根本不值一提。

“那该如何是好？”

“这个嘛，”忠胜再次回头望向南宫山。

“虽然有些忧虑……但想来大致无妨。”

“可确定吗？”

“若是打算冲击此处，那么差不多也该有些相应的迹象显露出来了。”

“唔。”

“然而，您看，南宫山一片森然寂静。”

“辛苦你了。”

家康打心底慰劳了重臣。

忠胜返回十九女池之后不久，家康便将本阵向前推进了约一千米，移到了关原驿的东侧。己方的败色已经浓厚到不得不如此的地步，家康已半是自暴自弃了。

<p style="margin-bottom:3em;"></p>

就在南宫山左后方升起两道烟柱的同时，毛利的总参谋吉川广家，便让自己麾下待命的三千余人，重新做好了随时可以出击的准备。

将士们吊起眉梢、紧张万分的样子，在广家看来有些可笑。他简直想对他们说声：好啦好啦，放松肩膀，别那么紧绷。

广家也向在南宫山各处布阵的己方诸将送去了传令，要求他们采取同样的措施：

“望诸队做好准备，只等我一声令下，便可随时出击。”

以狼烟为号，冲下山去，扼住袋口——这本是交付给毛利的任务。诸将全都知道这一点。如今狼烟已起，若再一味装傻，那也太奇怪了。

南宫山的阵势是：山顶为毛利秀元队，稍向北下是福原、宍户等重臣的诸部队，再往下则是吉川队。不知是有意还是偶然，吉川队的阵地正好堵住了南宫山的出口。也就是说，若是广家不让开道路，诸将连山麓都无法下去。

二三十分钟无事而过。但之后就不行了。山腰的吉川阵所，被催促出阵的诸将，以及安国寺、长曾我部、长束等人的传令兵挤得水泄不通。

战意最为旺盛的是宍户元续。这位曾在安浓津与分部光嘉上演过大名之间单挑的部将嚷道：

“侍从，你在磨蹭什么！就是现在！此刻冲下山去，胜利万无一失！”

叫得广家直往后退。若是放任不管，他恐怕就要说出“先锋我来当”之类的话了。

“我理解您的心情，”广家回答得极为殷勤。“但还请稍待片刻，等战机再成熟一些。”

安国寺惠琼的传令兵则受到了更粗暴些的对待。

“若对我的指挥有所不满，请便。”

广家一口回绝，毫不客气。

“请便？”

“我是说，你尽可自行出兵。惠琼阁下在安浓津时，不也未与我等商量，便擅自开战了吗？”

广家感到背上微微一阵战栗。这句话，我等待了十几年啊——他心想。

传令兵目瞪口呆地回去了。

若被人说“没有战意”，那才是广家最感意外的。自己早已在战斗了，不是与前面的敌人，而是与身后的友军战斗。

打发走传令兵们之后，广家进入了漫长的等待。这段孤独的时间，他全都用来回忆自己那不甚如意的、十几年的岁月了。

<p style="margin-bottom:3em;"></p>

对安国寺和三成的不满与怨愤，多得数也数不清：治少欣然收下了我赠送的雪舟真迹，却什么回礼也不给；治少曾想将我的领地交给秀元；治少不让我的爱女谒见太阁；治少妨碍了太阁访问吉川邸；治少和惠琼为了掩饰自己作战的失败，故意抹杀了我的军功；治少在太阁薨逝时，将我排除在了遗物分赠之外。若是将我践踏到如此地步，却还指望我念什么旧情，那你可就是个无可救药的傻瓜了。

话锋一转，广家想起了以智将之誉闻名的叔父——小早川隆景。

“本家之所以能享受到今日这般的繁荣，”隆景在晚年时常这般自夸道。“皆因得知本能寺凶变后，未曾追击那火急返回京畿的太阁。”

那话语中含着一种意味：正是自己让太阁取得了天下。

广家感动得灵魂都为之震颤。无论何时听来，这番话都蕴含着无尽的教诲。人情的微妙，以及作为武将进退取舍的要谛，仿佛全都凝聚其中——广家觉得，愚蠢地主张追击的父亲元春，以此为机走向了没落；而旁观的叔父，则获得了耀眼的名声与广阔的领地。

自己也想效仿叔父啊——广家想到。为了效仿，他才敢与家康携手，并像这样在山顶上观赏着合战。内府绝不会忘记吉川的恩情。正如太阁对待叔父那样，内府也定会厚厚地回报自己。吉川家将重获昔日的荣光。

这样就好，就该这样。

广家拼命地说服自己。的确，会有大量的牺牲者出现吧。但是，伟大的思想与情感，总是要求与之相称的牺牲的。

广家眯起眼睛，眺望着垂井的方向。

正对面可以看到池田辉政队，其稍左方则是浅野幸长队，正朝着这边布阵。

池田也好，浅野也好，都像被拔光了毛的鸡一样毫无遮掩，感觉极为靠不住。大概有一万人吧——广家无意识地估算着对方的兵力。到山麓有一千米，到池田队处似乎还要再加五百米。

广家感觉到一阵危险的诱惑悄悄潜入心头。毕竟，他是个战斗的行家。倘若此刻、就在这一瞬间冲下山去，将池田和浅野一举击溃，再直冲德川本阵的话，取下内府的首级，恐怕就像摘个桃子一样简单吧。唯一让他稍感遗憾的，就是自己不能这样做。

<p style="margin-bottom:3em;"></p>

此时，在南宫山的山顶上，那染着“一文字三星”纹章的幔幕之中，毛利宰相秀元正悠然自得地用着便当。倒不是因为饿，这位二十二岁的青年，是被逼入了不靠着吃便当来拖延时间、便无法维持体面的窘境。

“请您速速下山！”

催促参战的使者，这里也来了一拨又一拨。

“不要来催促我！”

秀元动了怒。

无需催促，青年本就战意高昂。仅毛利一家便有两万，若加上长曾我部、安国寺、长束各队，约三万大军可自由驱使。这是青年初次品尝到的、真正的豪奢。

此外，青年还有一个似乎必须奋力作战的理由。秀元的妻子，是太阁的亲弟弟——大和大纳言秀长的女儿。两位公主之中，姐姐被太阁收为养女，于五年前的文禄四年许配给了他。文禄四年，正是养父辉元有了亲生儿子，秀元自己失去毛利家继承者地位的那失意之年。

这桩交易无论怎么想，都是太阁一方吃亏。因为与他所付出的相比，能够期待的回报几乎等于零。但那位老权力者却热心地促成了这桩婚事。

秀元此时明白了：看来自己很受喜爱，在老人的眼中，自己是个将来能成大器的武将。

婚后，妻子很快病死了。秀元并不缺乏寻求新欢的机会。他很快就忘记了那个比他大三岁、既不算美也不算聪明的妻子。

然而，唯有那失意之中骤然到访的、混杂着惊讶与感激、令人不知如何是好的情感，却不可思议地逃脱了风化，留存了下来。

我被太阁宠爱过——这种感念，即使在眼下俯瞰着盆地时，也依然存在于青年心中。

据侦察兵报告，战况对西军压倒性有利。青年焦急起来。不单是为了报恩这种黏湿的感情，也是为了自身的荣光，秀元渴望取得辉煌的战果。

倘若吉川队没有布阵在半山腰，狼烟升起的同时，青年定已冲下那陡坡了吧。

“侍从到底在干什么！”

青年一次又一次地向参谋的阵地派去催促出阵的使者。

每次得到的，都是看似颇有道理的回答。

在此期间，栗原岭的各部队也频频来催促进军。青年便将诸将的意见转达给参谋，再将参谋的意见转达给诸将。不知不觉间，居中传话便成了他唯一的工作。

秀元对参谋没有丝毫怀疑。要懂得憎恨的可怕，他还太过年轻；更糟糕的是，对这位年龄相差如父的堂兄，青年是深深地敬畏着的。就连广家偶尔显露的乖僻，在他眼中，也仿佛是一位名战术家所难以避免的属性。

“啧，那就等吧。”

青年嘟囔道。

要说拨开吉川队、强行冲到平原上去的胆量，他是万万没有的。

只是，青年觉得对不住己方诸将。其中，尤其对不住安国寺。毕竟，自己虽只是一时，却曾被推举为毛利家的继承者，这事多赖惠琼的手腕。

“没办法，那就吃便当吧。”

那位啰嗦的琼长老，总不至于连战前填饱肚子也要抱怨吧。

“光我一个人吃不像话，”青年说道。“大家也吃吧。尽量慢慢吃。”

精美的漆器食盒被摆开了。出乎意料的是，便当很好吃。心中一边念着“对不住、对不住”，青年一边吃得咂舌作响。

就这样，每当诸家的传令兵跑来催促，便当便被用作延迟出马的借口。

青年一兵未动，迎来了败仗。这算什么呢。简直就像是特地为了吃便当才跑到关原来的。

合战之后，这位老好人的青年，不得不为“宰相殿的空便当”这一揶揄而苦恼不已。
