# 第八十九章 再闻足音 {-}

庆长六年十月十日，景胜主从获得了归国许可。

上杉家虽获准归国，毛利家却迟迟未见动静，辉元自前年以来，在木津邸一直过着近乎俘虏般的生活。九月末，辉元将嫡子秀就作为人质送往了江户。据说辉元已彻底自暴自弃。然而，与那黯淡的传闻相反，此人身上也有一桩让人不禁想咧嘴一笑的艳闻。

剃了头发、号宗瑞玄庵的辉元，将侧室从领地召来，颇享受那俘虏生活。甚至有传闻说，次子都已出生了。

与苦战连连的毛利相比，另一位大老则显示出登龙之势。九月三十日，秀忠三岁的珠姬，嫁给了肥前（前田利长）的养嗣子利常。无论哪一边，这些都是暗示今后盛衰之事。

<p style="margin-bottom:3em;"></p>

此后半月，准确说是十月十五日，上杉主从踏上了归途，途中造访了会津，于十一月二十八日，平安抵达羽州米泽。

归国后的主从，全力投入了殖产兴业。尤其是奖励了青苎、香菇、红花等的栽培，以及生丝绢织的生产。眼下的目标是五十万石。即使能增加到五十万石，能否养活庞大的家臣团，也仍是个疑问。

要摆脱困境的办法，大概也只有将庞大的家臣团裁员遣散这一条路了。

听到风声的诸位大名，争先恐后地将招聘使者派到了米泽。关原战败至今一年，未出一名叛徒的上杉家武士，养着总不会吃亏的。

家康也向甘糟景继伸出了触手。景继因白石城陷落后，一直受到景胜的严重冷遇而郁郁不得志。家康向这位景继开出了二万石的高价。但景继没有答应。

"臣之所以被主君疏远，是因未能守住白石城之故。臣深知己过。安敢怨恨主君。"

据说景继这样以头触地相辞。受命担任中间人的畠山蓬庵将此情报告后，家康屡次慨叹。

景胜在此之后，也终究没有原谅这位原白石城将。据《续武者物语》记载，景继死后，他的两个儿子最终也未得俸禄，在津轻一带流浪。

<p style="margin-bottom:3em;"></p>

景继拒绝了，但永井善左卫门却应了家康之招，后年出仕德川家，升任至御铠奉行。

小田切所左卫门应招至加贺，成为了肥前的宠臣。青木新兵卫和荻田主马则侍奉了木鼻的公子。新兵卫的知行不详，主马的知行则是一万石。

前田庆次郎利太也频频受到诸家的邀请。也有出价七千石、八千石的大名，但利太全都拒绝了。

"关原的败将、西军诸将，皆争先送质乞降。闻败报而不屈，抗战达一年，待和议成而后收兵的，唯有我家中纳言一人。堪为我主之人，除这位别无他选。"

这便是他的理由。

虽觉有些过于天真，但在那别扭的人眼中，景胜大概就是那样光鲜耀眼的存在吧。利太与兼续不知何故很是投缘，常聚集同好之士，讲解《源氏物语》之类。利太在米泽的知行，是五百石。

上杉的将士们虽散落到了别家，然而，即使是那样的他们，每逢佳节也从不曾少了给旧主的赠礼。

<p style="margin-bottom:3em;"></p>

移居米泽三年后，景胜第一次有了孩子。那是位五十岁的父亲了。

家记中记载道：

>"（五月五日）于米府城中，玉丸君诞生。其母为四辻大纳言公远卿之女，早先潜来米府，居本城。"

不过正室甲府夫人已于此三个月前，在伏见邸中去世了。

其实当初，上杉家的将士们对主人这位侍妾并无好感。他们深深敬慕着信玄的女儿，而且这位爱人的出现，极大地损害了主人一直恪守禁欲的神秘性。

就在侍妾来米泽后不久，米泽地方发生了一次小地震。于是口舌不饶人的那帮人，立刻将那场天灾归咎于她。说什么，是因为把那奇怪的女人从大门放了进来。但在玉丸出生时，则另当别论了。即便是带来天灾的侍妾，其生育能力也必须大受赞扬。

不过，这位四辻家的千金享受到作为生母的荣耀，时间并不长。产后仅三个月，她便追随甲府夫人去了。也就是说，景胜虽得到了亲生儿子，代价却是在这三个月前失去了正室夫人，三个月后失去了爱人。

景胜竟是出乎意料地溺爱孩子。这简直让人怀疑，此人难道就是那个在接到米泽减封令时，还豪言"武运衰退，于今何足为奇"的武将吗。爱人的出现与对亲生子的耽溺，或许正显示了昔日那飒爽的武功大名精神上的松懈。

<p style="margin-bottom:3em;"></p>

家康对这位昔日的大老同僚格外珍重。即使在被称为大御所大人之后，唯有面对这位米泽城主时，他仍执"中坛之礼"，即使在旅途中，一听闻景胜前来迎接，也必定会下轿，殷勤地弯腰，不忘说出犒劳的话语。

家康在格式与待遇上，也显示了特别的照应。江户参勤制度开始后，上杉家与越前松平家、黑田家、岛津家等相同，被定为大广间诘。除去上杉，其余二十二家全都是国持大名。

此外，家康还允许景胜在殿上之间立起屏风，让其待在其中。

"因为景胜不喜与人打交道嘛。"

这是表面上的理由。

虽说若非如此，跑来围观"与家康打过仗的男人"的年轻大名便会络绎不绝，这也是不得已，但不管怎么说，这都算是一个小小的特权。

<p style="margin-bottom:3em;"></p>

景胜的一举一动，悉数成了热门话题。

庆长十五年十二月，第二代将军秀忠曾驾临位于樱田门外的上杉邸。

"关原之后尚未过多久，竟有此事，实是意想不到。"

世间这样纷纷议论。但此际，景胜做了一件大胆之事：他将家中所有武士都迁到下屋敷，只与兼续两人出面迎接。料理也好，诸门的警备也罢，全数劳烦本多正信，悉委旗本众负责。做得何其彻底。

秀忠尽欢而归城。无人不称赞景胜是个明白事理之人。据说就连家康听闻此事，也是"大为欣赏"。

其实，当时景胜还搞了一个像他会做的事般的恶作剧。

为了迎接将军驾临，他在玄关前新造的厩舍上，把松川合战时从伊达政宗手中夺来的伊达家什物"法华经之幕"挂了出来。陪驾而来的政宗大为脸红，一副恼火的样子。

上杉家的武名由此远扬，于是便生出了这样的传说：立刻吃不消了的政宗提出用什物交换白石城，却被景胜毫不留情地拒绝了。

<p style="margin-bottom:3em;"></p>

似乎从这时起，这位米泽城主已开始成为活着便成为了传说的人物。

《上杉将士书上》中有这样的话：

>"（景胜）寡言少语，一生之中从未有人见过他笑的样子。有一次，一只被驯养的猴子，拿了景胜随手放下的头巾，爬上树，戴上那头巾，模仿主人的样子上下点头。景胜莞尔一笑。便连近侍们，看到景胜的笑容，也仅有这一次。"

还有这样的故事。那是在大坂冬之阵时，上杉队在大坂的志贵野口布阵时的事。

近侍们与不当班的年轻人正看得入神，忽然，景胜单骑巡视而来。

受了惊的年轻人们，纷纷逃窜到枪弹如雨般飞来的竹栅之外。

"比起敌人，竟是自家主人更可怕……"

诸大名对此咋舌不已。

<p style="margin-bottom:3em;"></p>

令人惊讶的是，兼续竟与"皇帝的秘书官"本多正信结下了友谊。这份友情始于二人共同负责米泽移封之事，并随岁月加深。

很快就有了"他这是在试图获取本多氏的好意，为自家谋利"这般不堪的流言，但兼续并不在意。

确实，也无法否定有那样的一面，但他对正信的尊敬，也绝非虚假。

两位执政官更通过让各自的长女与次男联姻，令友情的纽带愈发坚固。说到联姻，兼续的长男平八景明，是在正信的媒酌下，娶了近江膳所城主户田氏铁的女儿。

那时，曾发生过这样的事:

婚礼前夕，户田家将嫁妆运到了江户的直江邸。那朱漆的膳碗，还有金莳绘的器具，都极为精美。

直江家的管事立即将此报与兼续，并询问道：

"我家这边，是否也该准备配得上户田家的器具呢？"

"这太离谱了。"兼续大为不悦。"若是说没有对等的膳碗便不办婚礼，那就马上取消婚约。只要刀枪不生锈，那就足够了。"

什么朱漆膳碗，算什么东西。兼续是这么说的。

听闻此事的氏铁大为不安，但婚礼还是顺利举行了。

户田氏铁是著有《户田左门觉书》的文章家，也以持有激烈的反上杉、反直江情绪而知名。但是，自这场婚礼之后，这位膳所城主却成了最热心的兼续赞美者。氏铁对这位十六岁的女婿引以为傲，并对兼续作为监国的才能及其绚烂的诗才赞不绝口。

对于皇帝的秘书官与膳所城主对兼续所怀的这份敬意，幕阁终究无法忽视。

据说，即便是那位在诸大家老伏拜时也仅稍一颔首，为此颇有恶评的老中土井利胜，惟有面对兼续时，总会恭恭敬敬地低下头，在称呼时，也必不会忘记加上"山城守大人"的敬称。不过，利胜本人就是个兼续汉诗的热心爱好者，所以低个头什么的，也没什么好大惊小怪的。

<p style="margin-bottom:3em;"></p>

兼续于元和五年十二月，在江户邸中去世。享年六十。兼续不仅是上杉氏的执政。他更是一代民政家、诗人、军人。幕府特地下赐了银五十枚，以示对这位天下名士逝去的痛惜。

上杉景胜则在此四年后的元和九年三月去世，享年六十九岁。

<p style="margin-bottom:3em;"></p>

将时钟的指针再拨回到二十三年前吧。在庆长五年笼罩整个日本的战尘，直到合战的两年后，也即同七年十二月，才终于落定。

这年四月，抵抗到最后、顽冥不化的岛津氏，也终于从家康手中争取到了无罪赦免。岛津忠恒与家康的会见，是在年关将至的十二月二十八日，于伏见城中举行的。

家康朝着谒见的会场，大步流星地走去。

"真想让直政也列席啊。"家康心想。

为赦免岛津而拼命奔走的井伊直政，已在是年二月一日，因被岛津队士兵击中所受的铳创未能痊愈，以四十二岁的年纪，幽明异途了。

家康忽然停下了脚步。就在那时，老人将两年前初夏时与直政的那番对话，鲜明得如同昨日之事一般，想了起来。

那确实是在义弘被迫负责伏见城守备，又失意地离城之后不久的事。

那时，直政这样说道：

"倘若太阁的出现再迟个两三年，九州恐怕就除岛津之外，再无别的大名了吧。"

自己答道：

"我所喜欢的，正是这一点。无论是自赖朝公以来的显赫门第，还是那席卷九州的兵力，岛津都大有资格，在太阁死后与我德川争夺天下。"

"您这可是要叫醒那乖乖睡着的孩子啊。"

"你就是摇他，他也不会轻易醒的。那家是有武艺，但智略不足。你看着吧，岛津那惊慌失措的样子。那老人前一阵还在热心地巴结治部少。可现在，却差不多要成了我家的私兵了。"

"或许只是在装睡也未可知。岛津在下到萨摩三百年后，曾发狂般地大爆发过一次。"

"这么一说想起来了。浮在锦江湾上的那座岛叫什么来着。对了，不是有座火山，时会突然喷出黑烟，彷佛想起什么似的吗。"

"是樱岛吧。"

"对，就是那个。岛津下一次大爆发，大概也得再过个三百年左右了。"

记得和直政的对话就那样结束了。

家康做出了一副苦涩的表情。在这将全日本大名都收服于膝下的吉庆日子里，这可不是什么吉利的感觉。

然则，家康安慰自己道。到岛津的下一次大爆发，尚且有三百年的岁月。有三百年的话，德川之世至少能保个十代吧。

这不是挺好么。

家康重新打起精神，朝着谒见厅迈开了步子。

精神抖擞，大步地，将廊下踩得咚咚作响，一路而去。





