# (PART\*) 参考文献{-}

# 参考文献一览 {-}

『庆长年中卜斋记』（改定史籍集览）

『德川实纪』（国史大系）

『关原军记大成』（国史丛书）

『古今武家盛衰记』（国史丛书）

『新东鉴』（国史丛书）

『宽政重修诸家谱』（续群书类从完成会刊）

『断家谱』（续群书类从完成会刊）

『废绝录』（改定史籍集览）

『公卿补任』（国史大系）

『老人杂话』（改定史籍集览）

『落穗集』（改定史籍集览）

『常山纪谈』（汤浅元祯）

『名将言行录』（冈谷繁实）

『天正记』（大村由己）

『太阁记』（小濑甫庵）

『大阁下军记之内』（太田牛一）

『川角太阁记』（川角三郎右卫门）

『信长公记』（太田牛一）

『续群书类从（「黑田长政记」「清正记」「细川忠兴军功记」「胁坂记」其他）』

『武家事纪』（山鹿素行）

『三河物语』

『改正三河后风土记』

『福岛太夫殿御事』

『藤堂家觉书』

『蜂须贺蓬庵光明录』（长尾觉）

『上杉家御年谱』

『亚相公御夜话』

『梦幻物语』

『黑田家谱』

『阴德太平记』（香川正矩编）

『浅野家文书』

『关原阵辑录』

『池田家履历略记』

『太阁史料集』（战国史料丛书 新人物往来社）

『上杉史料集』（战国史料丛书 新人物往来社）

『真田史料集』（战国史料丛书 新人物往来社）

『武田史料集』（战国史料丛书 新人物往来社）

『岛津史料集』（战国史料丛书 新人物往来社）

『三百诸侯』（户川残花）

『上杉三代军记集成』

『大日本史料』（第十、十一、十二编）

『日本史』（弗洛伊斯著 松田毅一、川崎桃太译 中央公论社）

『日本战史』（参谋本部编）

『关原合战史料集』（藤井治左卫门编 新人物往来社）

『新编物语藩史』（儿玉幸多、北岛正元监修 新人物往来社）

『大名列传』（儿玉幸多、木村础编 新人物往来社）

『关原合战的全部』（小和田哲男著 新人物往来社）

『关原合战』（二木谦一著 中央公论社）

『关原之役——合战及其周边——』（松好贞夫著 新人物往来社）

『德川家康文书的研究』（中村孝也著 日本学术振兴会）

『德川家康』（山本七平著 President社）

『上杉氏的研究』（阿部洋辅编 吉川弘文馆）

『上杉景胜』（儿玉彰三郎著 儿玉彰三郎氏遗著刊行会）

『直江兼续传』（木村德卫著）

『小早川隆景』（渡边世祐、川上多助著 マッノ书店）

『大名与御伽众』（桑田忠亲著 有精堂出版）

『石田三成』（今井林太郎著 吉川弘文馆）

『安国寺惠琼』（河合正治著 吉川弘文馆）

『前田利家』（岩泽愿彦著 吉川弘文馆）

『长宗我部元亲』（山本大著 吉川弘文馆）

『岛井宗室』（田中健夫著 吉川弘文馆）

『淀君』（桑田忠亲著 吉川弘文馆）

『伊达政宗』（小林清治著 吉川弘文馆）

『丰臣时代史』（田中义成著 讲谈社）

『武家盛衰记』（南条范夫著 秋田书店）

『日本武将列传』（桑田忠亲著 秋田书店）

『城与女』（楠户义昭著 每日新闻社）

『战国的名城与武将们』（井上宗和著 Green Arrow出版社）

『乱世的遗训』（吉永正春著 苇书房）

『战国武将的本领』（户部新十郎著 读卖新闻社）

『战国武将传』（白石一郎著 文艺春秋）

『桃山时代的女性』（桑田忠亲著 吉川弘文馆）

『史传 黑田如水』（安藤英男著 すずき出版）

『岛津义弘的全部』（三木靖编 新人物往来社）

『真田幸村的全部』（小林计一郎编 新人物往来社）

『乱世的选择』（多岐一雄著 池田书店）

『关原合战』（会田雄次著 PHP研究所）

『辞世之语』（中西进著 中央公论社）

『德川家康』（北岛正元著 中央公论社）

『战国 前田一族』（能坂利雄著 新人物往来社）

『战国 细川一族』（户田敏夫著 新人物往来社）

『战国 宇喜多一族』（立石定夫著 新人物往来社）

『细川幽斋』（细川护贞著 求龙堂）

『庄子』（森三树三郎译注 中央公论社）

『无的思想』（森三树三郎著 讲谈社）

『庄子物语』（诸桥辙次著 讲谈社）

『贱岳七本枪』（德永真一郎著 每日新闻社）

『关原』（司马辽太郎著 新潮社）

『影之将军』（德永真一郎著 光文社）

『前田利家』（户部新十郎著 青树社）

『小六传』（户部新十郎著 PHP研究所）

『武田信玄』（新田次郎著 新人物往来社）

『篝火』（尾崎士郎著 六兴出版）

『巨大的企图』（堺屋太一著 文艺春秋）

『智将大谷刑部』（池内昭一著 新人物往来社）

『加藤清正』（海音寺潮五郎著 文艺春秋）

『武田·上杉军记』（小林计一郎著 新人物往来社）

『上杉谦信』（井上锐夫著 新人物往来社）

『上杉谦信的全部』（渡边庆一编 新人物往来社）

『石田三成』（安藤英男著 新人物往来社）

『石田三成的全部』（安藤英男编 新人物往来社）

『日本的历史』（中央公论社）

『现代视点 石田三成』（83·6 旺文社）

『决断／命运的关原』（「别册历史读本」88·3 新人物往来社）

『羽柴秀吉——怒涛的天下夺取——』（学研历史群像系列 387·7）

『关原之战——史上最大激突——』（学研历史群像系列 487·10）

『下克上／野望的战国大名』（「别册历史读本」32·10 新人物往来社）

『石田三成｜野望／关原决战——』（「别册历史读本」89·12 新人物往来社）

『德川家康——通向天下称霸之路——』（「别册历史读本」83·7 新人物往来社）

『President·特集德川三代』（88·1 President社）

『天下分目的关原』（「历史读本」81·1 新人物往来社）

『怪将·异将的战国史』（「历史读本」17·3 新人物往来社）

『战国七人的枭雄』（「历史读本」85·1 新人物往来社）

『战国胜者生存的战略』（「历史读本」83·1 新人物往来社）

『激突20万 关原之役』（「历史读本」722·9 新人物往来社）

『家康 通向霸王之路』（「临增历史读本」83·3 新人物往来社）

『战国成功物语』（「历史与人物」80·3 中央公论社）

『城之谜与武将的谋略』（「历史与人物」178·12 中央公论社）

『关原合战大特集』（「历史与旅」7·10 秋田书店）

『女人们的关原』（「历史读本」84·10 新人物往来社）

『谋略／从关原到大坂之阵』（「临增历史读本」85·12 新人物往来社）

『丰臣秀吉』（「河出人物读本」河出书房新社）

『德川家康』（「河出人物读本」河出书房新社）

『太阁秀吉 向海外的梦』（「向历史的招待」日本放送出版协会）

『决战关原』（「向历史的招待」日本放送出版协会）

『德川家康』（「向历史的招待」日本放送出版协会）

